/*******************************************************************************
 *  Copyright 2012-2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *  Licensed under the Apache License, Version 2.0 (the "License"). You may not use
 *  this file except in compliance with the License. A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 *  or in the "license" file accompanying this file.
 *  This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 *  CONDITIONS OF ANY KIND, either express or implied. See the License for the
 *  specific language governing permissions and limitations under the License.
 * *****************************************************************************
 *
 *  AWS Tools for Windows (TM) PowerShell (TM)
 *
 */

using System;
using System.Collections.Generic;
using System.Management.Automation;
using Amazon.PowerShell.Common;
using Amazon.Runtime;
using Amazon.Lambda;
using Amazon.Lambda.Model;

namespace Amazon.PowerShell.Cmdlets.LM
{
    /// <summary>
    /// Submits an invocation request to Lambda. Upon receiving the request, Lambda executes
    /// the specified cloud function asynchronously. To see the logs generated by the cloud
    /// function execution, see the CloudWatch logs console.
    /// 
    ///  
    /// <para>
    /// This operation requires permission for the <code>lambda:InvokeAsync</code> action.
    /// </para>
    /// <important> <p>This API is deprecated. We recommend you use <code>Invoke</code> API
    /// (see <a>Invoke</a>).</p> </important> <p>Submits an invocation request to AWS Lambda.
    /// Upon receiving the request, Lambda executes the specified function asynchronously.
    /// To see the logs generated by the Lambda function execution, see the CloudWatch Logs
    /// console.</p> <p>This operation requires permission for the
    /// <code>lambda:InvokeFunction</code> action.</p>
    /// <br/><br/>This operation is deprecated.
    /// </summary>
    [Cmdlet("Invoke", "LMFunctionAsync", SupportsShouldProcess = true, ConfirmImpact = ConfirmImpact.Low)]
    [OutputType("System.Int32")]
    [AWSCmdlet("Calls the Amazon Lambda InvokeAsync API operation.", Operation = new[] { "InvokeAsync" })]
    [AWSCmdletOutput("System.Int32",
        "This cmdlet returns a System.Int32 object.",
        "The service call response (type Amazon.Lambda.Model.InvokeAsyncResponse) can also be referenced from properties attached to the cmdlet entry in the $AWSHistory stack."
    )]
    [Obsolete("This Cmdlet is deprecated. We recommend to use the Invoke-LMFunction Cmdlet instead.")]
    public class InvokeLMFunctionAsyncCmdlet : AmazonLambdaClientCmdlet, IExecutor
    {
        #region Parameter FunctionName
        /// <summary>
        /// <para>
        /// The Lambda function name.
        /// </para>
        /// <para>
        /// Length constraints: Minimum length of 1. Maximum length of 140.
        /// </para>
        /// <para>
        /// Pattern: (arn:aws:lambda:)?([a-z]{2}-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?
        /// </para>
        /// </summary>
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = true, ValueFromPipeline = true)]
        public System.String FunctionName { get; set; }
        #endregion

        #region Parameter InvokeArg
        /// <summary>
        /// JSON that you want to provide to your Lambda function as input.
        /// </summary>
        [Parameter(Position = 1)]
        [Alias("InvokeArgs")]
        public System.String InvokeArg { get; set; }
        #endregion

        #region Parameter Force
        /// <summary>
        /// This parameter overrides confirmation prompts to force 
        /// the cmdlet to continue its operation. This parameter should always
        /// be used with caution.
        /// </summary>
        [Parameter]
        public SwitchParameter Force { get; set; }
        #endregion

        protected override void ProcessRecord()
        {
            base.ProcessRecord();

            if (!ConfirmShouldProceed(this.Force.IsPresent, this.FunctionName, "Invoke-LMFunctionAsync (InvokeAsync)"))
                return;

            var context = new CmdletContext
            {
                Region = this.Region,
                Credentials = this.CurrentCredentials, 
                FunctionName = this.FunctionName, 
                InvokeArgs = this.InvokeArg
            };

            var output = Execute(context) as CmdletOutput;
            ProcessOutput(output);
        }
        
        #region IExecutor Members
        
        public object Execute(ExecutorContext context)
        {
            var cmdletContext = context as CmdletContext;
            // create request
            var request = new InvokeAsyncRequest();
            
            if (cmdletContext.FunctionName != null)
            {
                request.FunctionName = cmdletContext.FunctionName;
            }

            request.InvokeArgs = cmdletContext.InvokeArgs ?? "{}";

            var client = Client ?? CreateClient(context.Credentials, context.Region);
            CmdletOutput output;
            
            // issue call
            try
            {
                var response = CallAWSServiceOperation(client, request);
                Dictionary<string, object> notes = null;
                object pipelineOutput = response.Status;
                output = new CmdletOutput
                {
                    PipelineOutput = pipelineOutput,
                    ServiceResponse = response,
                    Notes = notes
                };
            }
            catch (Exception e)
            {
                output = new CmdletOutput { ErrorResponse = e };
            }
            
            return output;
        }
        
        public ExecutorContext CreateContext()
        {
            return new CmdletContext();
        }

        #endregion

        #region AWS Service Operation Call

        private Amazon.Lambda.Model.InvokeAsyncResponse CallAWSServiceOperation(IAmazonLambda client, Amazon.Lambda.Model.InvokeAsyncRequest request)
        {
            Utils.Common.WriteVerboseEndpointMessage(this, client.Config, "Amazon Lambda", "InvokeAsync");

            try
            {
#if DESKTOP
                return client.InvokeAsync(request);
#elif CORECLR
                // todo: handle AggregateException and extract true service exception for rethrow
                var task = client.InvokeAsyncAsync(request);
                return task.Result;
#else
#error "Unknown build edition"
#endif
            }
            catch (AmazonServiceException exc)
            {
                var webException = exc.InnerException as System.Net.WebException;
                if (webException != null)
                {
                    throw new Exception(Utils.Common.FormatNameResolutionFailureMessage(client.Config, webException.Message), webException);
                }

                throw;
            }
        }

        #endregion

        internal class CmdletContext : ExecutorContext
        {
            public String FunctionName { get; set; }
            public String InvokeArgs { get; set; }
        }
        
    }
}
