#
# Module manifest for module 'AWS.Tools.EC2'
#

@{
    # Script module or binary module file associated with this manifest
    RootModule = 'AWS.Tools.EC2.dll'

    # Supported PSEditions
    CompatiblePSEditions = @('Core', 'Desktop')

    # Version number of this module.
    ModuleVersion = '0.0.0.0'

    # ID used to uniquely identify this module
    GUID = 'beb2445c-fd90-4fda-adf1-f8c955ce16dc'

    # Author of this module
    Author = 'Amazon.com, Inc'

    # Company or vendor of this module
    CompanyName = 'Amazon.com, Inc'

    # Copyright statement for this module
    Copyright = 'Copyright 2012-2024 Amazon.com, Inc. or its affiliates. All Rights Reserved.'

    # Description of the functionality provided by this module
    Description = 'The EC2 module of AWS Tools for PowerShell lets developers and administrators manage Amazon Elastic Compute Cloud (EC2) from the PowerShell scripting environment. In order to manage each AWS service, install the corresponding module (e.g. AWS.Tools.EC2, AWS.Tools.S3...).
The module AWS.Tools.Installer (https://www.powershellgallery.com/packages/AWS.Tools.Installer/) makes it easier to install, update and uninstall the AWS.Tools modules.
This version of AWS Tools for PowerShell is compatible with Windows PowerShell 5.1+ and PowerShell Core 6+ on Windows, Linux and macOS. When running on Windows PowerShell, .NET Framework 4.7.2 or newer is required. Alternative modules AWSPowerShell.NetCore and AWSPowerShell, provide support for all AWS services from a single module and also support older versions of Windows PowerShell and .NET Framework.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the PowerShell host required by this module
    PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    PowerShellHostVersion = ''

    # Minimum version of the .NET Framework required by this module
    DotNetFrameworkVersion = '4.7.2'

    # Minimum version of the common language runtime (CLR) required by this module
    CLRVersion = ''

    # Processor architecture (None, X86, Amd64, IA64) required by this module
    ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @(
        @{
            ModuleName = 'AWS.Tools.Common';
            RequiredVersion = '0.0.0.0';
            Guid = 'e5b05bf3-9eee-47b2-81f2-41ddc0501b86' }
    )

    # Assemblies that must be loaded prior to importing this module.
    RequiredAssemblies = @(
        'AWSSDK.EC2.dll'
    )

    # Script files (.ps1) that are run in the caller's environment prior to importing this module
    ScriptsToProcess = @(

    )

    # Type files (.ps1xml) to be loaded when importing this module
    TypesToProcess = @(

    )

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess = @(
        'AWS.Tools.EC2.Format.ps1xml'
    )

    # Modules to import as nested modules of the module specified in ModuleToProcess
    NestedModules = @(
        'AWS.Tools.EC2.Completers.psm1',
        'AWS.Tools.EC2.Aliases.psm1'
    )

    # Functions to export from this module
    FunctionsToExport = ''

    # Cmdlets to export from this module
    CmdletsToExport = @(
        'Add-EC2CapacityReservation', 
        'Add-EC2ClassicLinkVpc', 
        'Add-EC2InternetGateway', 
        'Add-EC2IpamByoasn', 
        'Add-EC2NetworkInterface', 
        'Add-EC2SecurityGroupToClientVpnTargetNetwork', 
        'Add-EC2Volume', 
        'Add-EC2VpnGateway', 
        'Approve-EC2AddressTransfer', 
        'Approve-EC2CapacityReservationBillingOwnership', 
        'Approve-EC2EndpointConnection', 
        'Approve-EC2ReservedInstancesExchangeQuote', 
        'Approve-EC2TransitGatewayMulticastDomainAssociation', 
        'Approve-EC2TransitGatewayPeeringAttachment', 
        'Approve-EC2TransitGatewayVpcAttachment', 
        'Approve-EC2VpcPeeringConnection', 
        'Confirm-EC2ProductInstance', 
        'Copy-EC2FpgaImage', 
        'Copy-EC2Image', 
        'Copy-EC2Snapshot', 
        'Deny-EC2CapacityReservationBillingOwnership', 
        'Deny-EC2EndpointConnection', 
        'Deny-EC2TransitGatewayMulticastDomainAssociation', 
        'Deny-EC2TransitGatewayPeeringAttachment', 
        'Deny-EC2TransitGatewayVpcAttachment', 
        'Deny-EC2VpcPeeringConnection', 
        'Disable-EC2AddressTransfer', 
        'Disable-EC2AwsNetworkPerformanceMetricSubscription', 
        'Disable-EC2EbsEncryptionByDefault', 
        'Disable-EC2FastLaunch', 
        'Disable-EC2FastSnapshotRestore', 
        'Disable-EC2Image', 
        'Disable-EC2ImageBlockPublicAccess', 
        'Disable-EC2ImageDeprecation', 
        'Disable-EC2ImageDeregistrationProtection', 
        'Disable-EC2IpamOrganizationAdminAccount', 
        'Disable-EC2SerialConsoleAccess', 
        'Disable-EC2SnapshotBlockPublicAccess', 
        'Disable-EC2TransitGatewayRouteTablePropagation', 
        'Disable-EC2VgwRoutePropagation', 
        'Disable-EC2VpcClassicLink', 
        'Disable-EC2VpcClassicLinkDnsSupport', 
        'Dismount-EC2ClassicLinkVpc', 
        'Dismount-EC2InternetGateway', 
        'Dismount-EC2NetworkInterface', 
        'Dismount-EC2VerifiedAccessTrustProvider', 
        'Dismount-EC2Volume', 
        'Dismount-EC2VpnGateway', 
        'Edit-EC2AddressAttribute', 
        'Edit-EC2AvailabilityZoneGroup', 
        'Edit-EC2CapacityReservation', 
        'Edit-EC2CapacityReservationFleet', 
        'Edit-EC2ClientVpnEndpoint', 
        'Edit-EC2DefaultCreditSpecification', 
        'Edit-EC2EbsDefaultKmsKeyId', 
        'Edit-EC2EndpointServicePermission', 
        'Edit-EC2Fleet', 
        'Edit-EC2FpgaImageAttribute', 
        'Edit-EC2Host', 
        'Edit-EC2IdentityIdFormat', 
        'Edit-EC2IdFormat', 
        'Edit-EC2ImageAttribute', 
        'Edit-EC2InstanceAttribute', 
        'Edit-EC2InstanceCapacityReservationAttribute', 
        'Edit-EC2InstanceCpuOption', 
        'Edit-EC2InstanceCreditSpecification', 
        'Edit-EC2InstanceEventStartTime', 
        'Edit-EC2InstanceEventWindow', 
        'Edit-EC2InstanceMaintenanceOption', 
        'Edit-EC2InstanceMetadataDefault', 
        'Edit-EC2InstanceMetadataOption', 
        'Edit-EC2InstancePlacement', 
        'Edit-EC2Ipam', 
        'Edit-EC2IpamPool', 
        'Edit-EC2IpamResourceCidr', 
        'Edit-EC2IpamResourceDiscovery', 
        'Edit-EC2IpamScope', 
        'Edit-EC2LaunchTemplate', 
        'Edit-EC2LocalGatewayRoute', 
        'Edit-EC2ManagedPrefixList', 
        'Edit-EC2NetworkInterfaceAttribute', 
        'Edit-EC2PrivateDnsNameOption', 
        'Edit-EC2ReservedInstance', 
        'Edit-EC2SecurityGroupRule', 
        'Edit-EC2SnapshotAttribute', 
        'Edit-EC2SnapshotTier', 
        'Edit-EC2SpotFleetRequest', 
        'Edit-EC2SubnetAttribute', 
        'Edit-EC2TrafficMirrorFilterNetworkService', 
        'Edit-EC2TrafficMirrorFilterRule', 
        'Edit-EC2TrafficMirrorSession', 
        'Edit-EC2TransitGateway', 
        'Edit-EC2TransitGatewayPrefixListReference', 
        'Edit-EC2TransitGatewayVpcAttachment', 
        'Edit-EC2VerifiedAccessEndpoint', 
        'Edit-EC2VerifiedAccessEndpointPolicy', 
        'Edit-EC2VerifiedAccessGroup', 
        'Edit-EC2VerifiedAccessGroupPolicy', 
        'Edit-EC2VerifiedAccessInstance', 
        'Edit-EC2VerifiedAccessInstanceLoggingConfiguration', 
        'Edit-EC2VerifiedAccessTrustProvider', 
        'Edit-EC2Volume', 
        'Edit-EC2VolumeAttribute', 
        'Edit-EC2VpcAttribute', 
        'Edit-EC2VpcBlockPublicAccessExclusion', 
        'Edit-EC2VpcBlockPublicAccessOption', 
        'Edit-EC2VpcEndpoint', 
        'Edit-EC2VpcEndpointConnectionNotification', 
        'Edit-EC2VpcEndpointServiceConfiguration', 
        'Edit-EC2VpcEndpointServicePayerResponsibility', 
        'Edit-EC2VpcPeeringConnectionOption', 
        'Edit-EC2VpcTenancy', 
        'Edit-EC2VpnConnection', 
        'Edit-EC2VpnConnectionOption', 
        'Edit-EC2VpnTunnelCertificate', 
        'Edit-EC2VpnTunnelOption', 
        'Enable-EC2AddressTransfer', 
        'Enable-EC2AwsNetworkPerformanceMetricSubscription', 
        'Enable-EC2EbsEncryptionByDefault', 
        'Enable-EC2FastLaunch', 
        'Enable-EC2FastSnapshotRestore', 
        'Enable-EC2Image', 
        'Enable-EC2ImageBlockPublicAccess', 
        'Enable-EC2ImageDeprecation', 
        'Enable-EC2ImageDeregistrationProtection', 
        'Enable-EC2IpamOrganizationAdminAccount', 
        'Enable-EC2ReachabilityAnalyzerOrganizationSharing', 
        'Enable-EC2SerialConsoleAccess', 
        'Enable-EC2SnapshotBlockPublicAccess', 
        'Enable-EC2TransitGatewayRouteTablePropagation', 
        'Enable-EC2VgwRoutePropagation', 
        'Enable-EC2VolumeIO', 
        'Enable-EC2VpcClassicLink', 
        'Enable-EC2VpcClassicLinkDnsSupport', 
        'Export-EC2ClientVpnClientCertificateRevocationList', 
        'Export-EC2ClientVpnClientConfiguration', 
        'Export-EC2Image', 
        'Export-EC2TransitGatewayRoute', 
        'Get-EC2AccountAttribute', 
        'Get-EC2Address', 
        'Get-EC2AddressesAttribute', 
        'Get-EC2AddressTransfer', 
        'Get-EC2AggregateIdFormat', 
        'Get-EC2AssociatedEnclaveCertificateIamRole', 
        'Get-EC2AssociatedIpv6PoolCidr', 
        'Get-EC2AvailabilityZone', 
        'Get-EC2AwsNetworkPerformanceData', 
        'Get-EC2AwsNetworkPerformanceMetricSubscription', 
        'Get-EC2BundleTask', 
        'Get-EC2ByoipCidr', 
        'Get-EC2CapacityBlockOffering', 
        'Get-EC2CapacityReservation', 
        'Get-EC2CapacityReservationBillingRequest', 
        'Get-EC2CapacityReservationFleet', 
        'Get-EC2CapacityReservationUsage', 
        'Get-EC2CarrierGateway', 
        'Get-EC2ClassicLinkInstance', 
        'Get-EC2ClientVpnAuthorizationRule', 
        'Get-EC2ClientVpnConnection', 
        'Get-EC2ClientVpnEndpoint', 
        'Get-EC2ClientVpnRoute', 
        'Get-EC2ClientVpnTargetNetwork', 
        'Get-EC2CoipPool', 
        'Get-EC2CoipPoolUsage', 
        'Get-EC2ConsoleOutput', 
        'Get-EC2ConsoleScreenshot', 
        'Get-EC2CreditSpecification', 
        'Get-EC2CustomerGateway', 
        'Get-EC2DefaultCreditSpecification', 
        'Get-EC2DhcpOption', 
        'Get-EC2EbsDefaultKmsKeyId', 
        'Get-EC2EbsEncryptionByDefault', 
        'Get-EC2EgressOnlyInternetGatewayList', 
        'Get-EC2ElasticGpu', 
        'Get-EC2EndpointConnection', 
        'Get-EC2EndpointConnectionNotification', 
        'Get-EC2EndpointServiceConfiguration', 
        'Get-EC2EndpointServicePermission', 
        'Get-EC2ExportImageTask', 
        'Get-EC2ExportTask', 
        'Get-EC2FastLaunchImage', 
        'Get-EC2FastSnapshotRestore', 
        'Get-EC2FleetHistory', 
        'Get-EC2FleetInstanceList', 
        'Get-EC2FleetList', 
        'Get-EC2FlowLog', 
        'Get-EC2FlowLogsIntegrationTemplate', 
        'Get-EC2FpgaImage', 
        'Get-EC2FpgaImageAttribute', 
        'Get-EC2GroupsForCapacityReservation', 
        'Get-EC2Host', 
        'Get-EC2HostReservation', 
        'Get-EC2HostReservationOffering', 
        'Get-EC2HostReservationPurchasePreview', 
        'Get-EC2IamInstanceProfileAssociation', 
        'Get-EC2IdentityIdFormat', 
        'Get-EC2IdFormat', 
        'Get-EC2Image', 
        'Get-EC2ImageAttribute', 
        'Get-EC2ImageBlockPublicAccessState', 
        'Get-EC2ImageByName', 
        'Get-EC2ImagesInRecycleBinList', 
        'Get-EC2ImportImageTask', 
        'Get-EC2ImportSnapshotTask', 
        'Get-EC2Instance', 
        'Get-EC2InstanceAttribute', 
        'Get-EC2InstanceConnectEndpoint', 
        'Get-EC2InstanceEventNotificationAttribute', 
        'Get-EC2InstanceEventWindow', 
        'Get-EC2InstanceImageMetadata', 
        'Get-EC2InstanceMetadata', 
        'Get-EC2InstanceMetadataDefault', 
        'Get-EC2InstanceStatus', 
        'Get-EC2InstanceTopology', 
        'Get-EC2InstanceTpmEkPub', 
        'Get-EC2InstanceType', 
        'Get-EC2InstanceTypeOffering', 
        'Get-EC2InstanceTypesFromInstanceRequirement', 
        'Get-EC2InstanceUefiData', 
        'Get-EC2InternetGateway', 
        'Get-EC2Ipam', 
        'Get-EC2IpamAddressHistory', 
        'Get-EC2IpamByoasn', 
        'Get-EC2IpamDiscoveredAccount', 
        'Get-EC2IpamDiscoveredPublicAddress', 
        'Get-EC2IpamDiscoveredResourceCidr', 
        'Get-EC2IpamExternalResourceVerificationToken', 
        'Get-EC2IpamPool', 
        'Get-EC2IpamPoolAllocation', 
        'Get-EC2IpamPoolCidr', 
        'Get-EC2IpamResourceCidr', 
        'Get-EC2IpamResourceDiscovery', 
        'Get-EC2IpamResourceDiscoveryAssociation', 
        'Get-EC2IpamScope', 
        'Get-EC2Ipv6Pool', 
        'Get-EC2KeyPair', 
        'Get-EC2LaunchTemplateData', 
        'Get-EC2LocalGateway', 
        'Get-EC2LocalGatewayRouteTable', 
        'Get-EC2LocalGatewayRouteTableVirtualInterfaceGroupAssociation', 
        'Get-EC2LocalGatewayRouteTableVpcAssociation', 
        'Get-EC2LocalGatewayVirtualInterface', 
        'Get-EC2LocalGatewayVirtualInterfaceGroup', 
        'Get-EC2LockedSnapshot', 
        'Get-EC2MacHost', 
        'Get-EC2ManagedPrefixList', 
        'Get-EC2ManagedPrefixListAssociation', 
        'Get-EC2ManagedPrefixListEntry', 
        'Get-EC2MovingAddress', 
        'Get-EC2NatGateway', 
        'Get-EC2NetworkAcl', 
        'Get-EC2NetworkInsightsAccessScope', 
        'Get-EC2NetworkInsightsAccessScopeAnalysis', 
        'Get-EC2NetworkInsightsAccessScopeAnalysisFinding', 
        'Get-EC2NetworkInsightsAccessScopeContent', 
        'Get-EC2NetworkInsightsAnalysis', 
        'Get-EC2NetworkInsightsPath', 
        'Get-EC2NetworkInterface', 
        'Get-EC2NetworkInterfaceAttribute', 
        'Get-EC2NetworkInterfacePermission', 
        'Get-EC2PasswordData', 
        'Get-EC2PlacementGroup', 
        'Get-EC2PrefixList', 
        'Get-EC2PrincipalIdFormat', 
        'Get-EC2PublicIpv4Pool', 
        'Get-EC2Region', 
        'Get-EC2ReplaceRootVolumeTask', 
        'Get-EC2ReservedInstance', 
        'Get-EC2ReservedInstancesExchangeQuote', 
        'Get-EC2ReservedInstancesListing', 
        'Get-EC2ReservedInstancesModification', 
        'Get-EC2ReservedInstancesOffering', 
        'Get-EC2RouteTable', 
        'Get-EC2ScheduledInstance', 
        'Get-EC2ScheduledInstanceAvailability', 
        'Get-EC2SecurityGroup', 
        'Get-EC2SecurityGroupReference', 
        'Get-EC2SecurityGroupRule', 
        'Get-EC2SecurityGroupsForVpc', 
        'Get-EC2SecurityGroupVpcAssociation', 
        'Get-EC2SerialConsoleAccessStatus', 
        'Get-EC2Snapshot', 
        'Get-EC2SnapshotAttribute', 
        'Get-EC2SnapshotBlockPublicAccessState', 
        'Get-EC2SnapshotsInRecycleBinList', 
        'Get-EC2SnapshotTierStatus', 
        'Get-EC2SpotDatafeedSubscription', 
        'Get-EC2SpotFleetInstance', 
        'Get-EC2SpotFleetRequest', 
        'Get-EC2SpotFleetRequestHistory', 
        'Get-EC2SpotInstanceRequest', 
        'Get-EC2SpotPlacementScore', 
        'Get-EC2SpotPriceHistory', 
        'Get-EC2StaleSecurityGroup', 
        'Get-EC2StoreImageTask', 
        'Get-EC2Subnet', 
        'Get-EC2SubnetCidrReservation', 
        'Get-EC2Tag', 
        'Get-EC2Template', 
        'Get-EC2TemplateVersion', 
        'Get-EC2TrafficMirrorFilter', 
        'Get-EC2TrafficMirrorFilterRule', 
        'Get-EC2TrafficMirrorSession', 
        'Get-EC2TrafficMirrorTarget', 
        'Get-EC2TransitGateway', 
        'Get-EC2TransitGatewayAttachment', 
        'Get-EC2TransitGatewayAttachmentPropagation', 
        'Get-EC2TransitGatewayConnect', 
        'Get-EC2TransitGatewayConnectPeer', 
        'Get-EC2TransitGatewayMulticastDomain', 
        'Get-EC2TransitGatewayMulticastDomainAssociation', 
        'Get-EC2TransitGatewayPeeringAttachment', 
        'Get-EC2TransitGatewayPolicyTable', 
        'Get-EC2TransitGatewayPolicyTableAssociation', 
        'Get-EC2TransitGatewayPolicyTableEntry', 
        'Get-EC2TransitGatewayPrefixListReference', 
        'Get-EC2TransitGatewayRouteTable', 
        'Get-EC2TransitGatewayRouteTableAnnouncement', 
        'Get-EC2TransitGatewayRouteTableAssociation', 
        'Get-EC2TransitGatewayRouteTablePropagation', 
        'Get-EC2TransitGatewayVpcAttachment', 
        'Get-EC2TrunkInterfaceAssociation', 
        'Get-EC2VerifiedAccessEndpoint', 
        'Get-EC2VerifiedAccessEndpointPolicy', 
        'Get-EC2VerifiedAccessGroup', 
        'Get-EC2VerifiedAccessGroupPolicy', 
        'Get-EC2VerifiedAccessInstance', 
        'Get-EC2VerifiedAccessInstanceLoggingConfiguration', 
        'Get-EC2VerifiedAccessTrustProvider', 
        'Get-EC2Volume', 
        'Get-EC2VolumeAttribute', 
        'Get-EC2VolumeModification', 
        'Get-EC2VolumeStatus', 
        'Get-EC2Vpc', 
        'Get-EC2VpcAttribute', 
        'Get-EC2VpcBlockPublicAccessExclusion', 
        'Get-EC2VpcBlockPublicAccessOption', 
        'Get-EC2VpcClassicLink', 
        'Get-EC2VpcClassicLinkDnsSupport', 
        'Get-EC2VpcEndpoint', 
        'Get-EC2VpcEndpointService', 
        'Get-EC2VpcPeeringConnection', 
        'Get-EC2VpnConnection', 
        'Get-EC2VpnConnectionDeviceSampleConfiguration', 
        'Get-EC2VpnConnectionDeviceType', 
        'Get-EC2VpnGateway', 
        'Get-EC2VpnTunnelReplacementStatus', 
        'Grant-EC2ClientVpnIngress', 
        'Grant-EC2SecurityGroupEgress', 
        'Grant-EC2SecurityGroupIngress', 
        'Import-EC2ClientVpnClientCertificateRevocationList', 
        'Import-EC2Image', 
        'Import-EC2KeyPair', 
        'Import-EC2Snapshot', 
        'Lock-EC2Snapshot', 
        'Mount-EC2VerifiedAccessTrustProvider', 
        'Move-EC2AddressToVpc', 
        'Move-EC2ByoipCidrToIpam', 
        'Move-EC2CapacityReservationInstance', 
        'New-EC2Address', 
        'New-EC2CapacityReservationBySplitting', 
        'New-EC2CapacityReservationFleet', 
        'New-EC2CarrierGateway', 
        'New-EC2ClientVpnEndpoint', 
        'New-EC2ClientVpnRoute', 
        'New-EC2CoipCidr', 
        'New-EC2CoipPool', 
        'New-EC2CustomerGateway', 
        'New-EC2DefaultSubnet', 
        'New-EC2DefaultVpc', 
        'New-EC2DhcpOption', 
        'New-EC2EC2CapacityBlock', 
        'New-EC2EgressOnlyInternetGateway', 
        'New-EC2Fleet', 
        'New-EC2FlowLog', 
        'New-EC2FpgaImage', 
        'New-EC2Host', 
        'New-EC2HostReservation', 
        'New-EC2Image', 
        'New-EC2Instance', 
        'New-EC2InstanceBundle', 
        'New-EC2InstanceConnectEndpoint', 
        'New-EC2InstanceEventWindow', 
        'New-EC2InstanceExportTask', 
        'New-EC2InternetGateway', 
        'New-EC2Ipam', 
        'New-EC2IpamExternalResourceVerificationToken', 
        'New-EC2IpamPool', 
        'New-EC2IpamPoolCidr', 
        'New-EC2IpamResourceDiscovery', 
        'New-EC2IpamScope', 
        'New-EC2KeyPair', 
        'New-EC2LaunchTemplate', 
        'New-EC2LaunchTemplateVersion', 
        'New-EC2LocalGatewayRoute', 
        'New-EC2LocalGatewayRouteTable', 
        'New-EC2LocalGatewayRouteTableVirtualInterfaceGroupAssociation', 
        'New-EC2LocalGatewayRouteTableVpcAssociation', 
        'New-EC2ManagedPrefixList', 
        'New-EC2NatGateway', 
        'New-EC2NetworkAcl', 
        'New-EC2NetworkAclEntry', 
        'New-EC2NetworkInsightsAccessScope', 
        'New-EC2NetworkInsightsPath', 
        'New-EC2NetworkInterface', 
        'New-EC2NetworkInterfacePermission', 
        'New-EC2PlacementGroup', 
        'New-EC2PublicIpv4Pool', 
        'New-EC2ReplaceRootVolumeTask', 
        'New-EC2ReservedInstance', 
        'New-EC2ReservedInstancesListing', 
        'New-EC2RestoreImageTask', 
        'New-EC2Route', 
        'New-EC2RouteTable', 
        'New-EC2ScheduledInstance', 
        'New-EC2ScheduledInstancePurchase', 
        'New-EC2SecurityGroup', 
        'New-EC2Snapshot', 
        'New-EC2SnapshotBatch', 
        'New-EC2SpotDatafeedSubscription', 
        'New-EC2StoreImageTask', 
        'New-EC2Subnet', 
        'New-EC2SubnetCidrReservation', 
        'New-EC2Tag', 
        'New-EC2TrafficMirrorFilter', 
        'New-EC2TrafficMirrorFilterRule', 
        'New-EC2TrafficMirrorSession', 
        'New-EC2TrafficMirrorTarget', 
        'New-EC2TransitGateway', 
        'New-EC2TransitGatewayConnect', 
        'New-EC2TransitGatewayConnectPeer', 
        'New-EC2TransitGatewayMulticastDomain', 
        'New-EC2TransitGatewayPeeringAttachment', 
        'New-EC2TransitGatewayPolicyTable', 
        'New-EC2TransitGatewayPrefixListReference', 
        'New-EC2TransitGatewayRoute', 
        'New-EC2TransitGatewayRouteTable', 
        'New-EC2TransitGatewayRouteTableAnnouncement', 
        'New-EC2TransitGatewayVpcAttachment', 
        'New-EC2VerifiedAccessEndpoint', 
        'New-EC2VerifiedAccessGroup', 
        'New-EC2VerifiedAccessInstance', 
        'New-EC2VerifiedAccessTrustProvider', 
        'New-EC2Volume', 
        'New-EC2Vpc', 
        'New-EC2VpcBlockPublicAccessExclusion', 
        'New-EC2VpcEndpoint', 
        'New-EC2VpcEndpointConnectionNotification', 
        'New-EC2VpcEndpointServiceConfiguration', 
        'New-EC2VpcPeeringConnection', 
        'New-EC2VpnConnection', 
        'New-EC2VpnConnectionRoute', 
        'New-EC2VpnGateway', 
        'Register-EC2Address', 
        'Register-EC2ByoipCidr', 
        'Register-EC2CapacityReservationBillingOwner', 
        'Register-EC2ClientVpnTargetNetwork', 
        'Register-EC2DhcpOption', 
        'Register-EC2EnclaveCertificateIamRole', 
        'Register-EC2IamInstanceProfile', 
        'Register-EC2Image', 
        'Register-EC2InstanceEventNotificationAttribute', 
        'Register-EC2InstanceEventWindow', 
        'Register-EC2IpamByoasn', 
        'Register-EC2IpamPoolCidr', 
        'Register-EC2IpamResourceDiscovery', 
        'Register-EC2Ipv6AddressList', 
        'Register-EC2NatGatewayAddress', 
        'Register-EC2PrivateIpAddress', 
        'Register-EC2PrivateNatGatewayAddress', 
        'Register-EC2PublicIpv4PoolCidr', 
        'Register-EC2RouteTable', 
        'Register-EC2SecurityGroupVpc', 
        'Register-EC2SubnetCidrBlock', 
        'Register-EC2TransitGatewayMulticastDomain', 
        'Register-EC2TransitGatewayMulticastGroupMember', 
        'Register-EC2TransitGatewayMulticastGroupSource', 
        'Register-EC2TransitGatewayPolicyTable', 
        'Register-EC2TransitGatewayRouteTable', 
        'Register-EC2TrunkInterface', 
        'Register-EC2VpcCidrBlock', 
        'Remove-EC2Address', 
        'Remove-EC2CapacityReservation', 
        'Remove-EC2CarrierGateway', 
        'Remove-EC2ClientVpnEndpoint', 
        'Remove-EC2ClientVpnRoute', 
        'Remove-EC2CoipCidr', 
        'Remove-EC2CoipPool', 
        'Remove-EC2CustomerGateway', 
        'Remove-EC2DhcpOption', 
        'Remove-EC2EgressOnlyInternetGateway', 
        'Remove-EC2EndpointConnectionNotification', 
        'Remove-EC2EndpointServiceConfiguration', 
        'Remove-EC2Fleet', 
        'Remove-EC2FlowLog', 
        'Remove-EC2FpgaImage', 
        'Remove-EC2Host', 
        'Remove-EC2Instance', 
        'Remove-EC2InstanceConnectEndpoint', 
        'Remove-EC2InstanceEventWindow', 
        'Remove-EC2InternetGateway', 
        'Remove-EC2Ipam', 
        'Remove-EC2IpamByoasn', 
        'Remove-EC2IpamExternalResourceVerificationToken', 
        'Remove-EC2IpamPool', 
        'Remove-EC2IpamPoolAllocation', 
        'Remove-EC2IpamResourceDiscovery', 
        'Remove-EC2IpamScope', 
        'Remove-EC2KeyPair', 
        'Remove-EC2LaunchTemplate', 
        'Remove-EC2LocalGatewayRoute', 
        'Remove-EC2LocalGatewayRouteTable', 
        'Remove-EC2LocalGatewayRouteTableVirtualInterfaceGroupAssociation', 
        'Remove-EC2LocalGatewayRouteTableVpcAssociation', 
        'Remove-EC2ManagedPrefixList', 
        'Remove-EC2NatGateway', 
        'Remove-EC2NetworkAcl', 
        'Remove-EC2NetworkAclEntry', 
        'Remove-EC2NetworkInsightsAccessScope', 
        'Remove-EC2NetworkInsightsAccessScopeAnalysis', 
        'Remove-EC2NetworkInsightsAnalysis', 
        'Remove-EC2NetworkInsightsPath', 
        'Remove-EC2NetworkInterface', 
        'Remove-EC2NetworkInterfacePermission', 
        'Remove-EC2PlacementGroup', 
        'Remove-EC2PublicIpv4Pool', 
        'Remove-EC2QueuedReservedInstance', 
        'Remove-EC2Route', 
        'Remove-EC2RouteTable', 
        'Remove-EC2SecurityGroup', 
        'Remove-EC2Snapshot', 
        'Remove-EC2SpotDatafeedSubscription', 
        'Remove-EC2Subnet', 
        'Remove-EC2SubnetCidrReservation', 
        'Remove-EC2Tag', 
        'Remove-EC2TemplateVersion', 
        'Remove-EC2TrafficMirrorFilter', 
        'Remove-EC2TrafficMirrorFilterRule', 
        'Remove-EC2TrafficMirrorSession', 
        'Remove-EC2TrafficMirrorTarget', 
        'Remove-EC2TransitGateway', 
        'Remove-EC2TransitGatewayConnect', 
        'Remove-EC2TransitGatewayConnectPeer', 
        'Remove-EC2TransitGatewayMulticastDomain', 
        'Remove-EC2TransitGatewayPeeringAttachment', 
        'Remove-EC2TransitGatewayPolicyTable', 
        'Remove-EC2TransitGatewayPrefixListReference', 
        'Remove-EC2TransitGatewayRoute', 
        'Remove-EC2TransitGatewayRouteTable', 
        'Remove-EC2TransitGatewayRouteTableAnnouncement', 
        'Remove-EC2TransitGatewayVpcAttachment', 
        'Remove-EC2VerifiedAccessEndpoint', 
        'Remove-EC2VerifiedAccessGroup', 
        'Remove-EC2VerifiedAccessInstance', 
        'Remove-EC2VerifiedAccessTrustProvider', 
        'Remove-EC2Volume', 
        'Remove-EC2Vpc', 
        'Remove-EC2VpcBlockPublicAccessExclusion', 
        'Remove-EC2VpcEndpoint', 
        'Remove-EC2VpcPeeringConnection', 
        'Remove-EC2VpnConnection', 
        'Remove-EC2VpnConnectionRoute', 
        'Remove-EC2VpnGateway', 
        'Request-EC2SpotFleet', 
        'Request-EC2SpotInstance', 
        'Reset-EC2AddressAttribute', 
        'Reset-EC2EbsDefaultKmsKeyId', 
        'Reset-EC2FpgaImageAttribute', 
        'Reset-EC2ImageAttribute', 
        'Reset-EC2InstanceAttribute', 
        'Reset-EC2NetworkInterfaceAttribute', 
        'Reset-EC2SnapshotAttribute', 
        'Restart-EC2Instance', 
        'Restore-EC2AddressToClassic', 
        'Restore-EC2ImageFromRecycleBin', 
        'Restore-EC2ManagedPrefixListVersion', 
        'Restore-EC2SnapshotFromRecycleBin', 
        'Restore-EC2SnapshotTier', 
        'Revoke-EC2ClientVpnIngress', 
        'Revoke-EC2SecurityGroupEgress', 
        'Revoke-EC2SecurityGroupIngress', 
        'Search-EC2LocalGatewayRoute', 
        'Search-EC2TransitGatewayMulticastGroup', 
        'Search-EC2TransitGatewayRoute', 
        'Send-EC2DiagnosticInterrupt', 
        'Send-EC2InstanceStatus', 
        'Set-EC2IamInstanceProfileAssociation', 
        'Set-EC2NetworkAclAssociation', 
        'Set-EC2NetworkAclEntry', 
        'Set-EC2Route', 
        'Set-EC2RouteTableAssociation', 
        'Set-EC2TransitGatewayRoute', 
        'Set-EC2VpnTunnel', 
        'Start-EC2ByoipCidrAdvertisement', 
        'Start-EC2Instance', 
        'Start-EC2InstanceMonitoring', 
        'Start-EC2NetworkInsightsAccessScopeAnalysis', 
        'Start-EC2NetworkInsightsAnalysis', 
        'Start-EC2VpcEndpointServicePrivateDnsVerification', 
        'Stop-EC2BundleTask', 
        'Stop-EC2ByoipCidrAdvertisement', 
        'Stop-EC2CapacityReservationFleet', 
        'Stop-EC2ClientVpnConnection', 
        'Stop-EC2ExportTask', 
        'Stop-EC2ImageLaunchPermission', 
        'Stop-EC2ImportTask', 
        'Stop-EC2Instance', 
        'Stop-EC2InstanceMonitoring', 
        'Stop-EC2ReservedInstancesListing', 
        'Stop-EC2SpotFleetRequest', 
        'Stop-EC2SpotInstanceRequest', 
        'Unlock-EC2Snapshot', 
        'Unregister-EC2Address', 
        'Unregister-EC2ByoipCidr', 
        'Unregister-EC2CapacityReservationBillingOwner', 
        'Unregister-EC2ClientVpnTargetNetwork', 
        'Unregister-EC2EnclaveCertificateIamRole', 
        'Unregister-EC2IamInstanceProfile', 
        'Unregister-EC2Image', 
        'Unregister-EC2InstanceEventNotificationAttribute', 
        'Unregister-EC2InstanceEventWindow', 
        'Unregister-EC2IpamByoasn', 
        'Unregister-EC2IpamPoolCidr', 
        'Unregister-EC2IpamResourceDiscovery', 
        'Unregister-EC2Ipv6AddressList', 
        'Unregister-EC2NatGatewayAddress', 
        'Unregister-EC2PrivateIpAddress', 
        'Unregister-EC2PrivateNatGatewayAddress', 
        'Unregister-EC2PublicIpv4PoolCidr', 
        'Unregister-EC2RouteTable', 
        'Unregister-EC2SecurityGroupVpc', 
        'Unregister-EC2SubnetCidrBlock', 
        'Unregister-EC2TransitGatewayMulticastDomain', 
        'Unregister-EC2TransitGatewayMulticastGroupMember', 
        'Unregister-EC2TransitGatewayMulticastGroupSource', 
        'Unregister-EC2TransitGatewayPolicyTable', 
        'Unregister-EC2TransitGatewayRouteTable', 
        'Unregister-EC2TrunkInterface', 
        'Unregister-EC2VpcCidrBlock', 
        'Update-EC2SecurityGroupRuleEgressDescription', 
        'Update-EC2SecurityGroupRuleIngressDescription')

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module
    AliasesToExport = @(
        'Confirm-EC2ReservedInstancesExchangeQuote', 
        'Confirm-EC2TransitGatewayPeeringAttachment', 
        'Confirm-EC2TransitGatewayVpcAttachment', 
        'Confirm-EC2EndpointConnection', 
        'Confirm-EC2VpcPeeringConnection', 
        'New-EC2Hosts', 
        'New-EC2FlowLogs', 
        'Remove-EC2FlowLogs', 
        'Get-EC2AccountAttributes', 
        'Get-EC2ExportTasks', 
        'Get-EC2FlowLogs', 
        'Get-EC2Hosts', 
        'Get-EC2ReservedInstancesModifications', 
        'Get-EC2Snapshots', 
        'Get-EC2VpcPeeringConnections', 
        'Edit-EC2Hosts', 
        'ReleaseHosts')

    # List of all modules packaged with this module
    ModuleList = @()

    # List of all files packaged with this module
    FileList = @(
        'AWS.Tools.EC2.dll-Help.xml'
    )

    # Private data to pass to the module specified in ModuleToProcess
    PrivateData = @{

        PSData = @{
            Tags = @('AWS', 'cloud', 'Windows', 'PSEdition_Desktop', 'PSEdition_Core', 'Linux', 'MacOS', 'Mac')
            LicenseUri = 'https://aws.amazon.com/apache-2-0/'
            ProjectUri = 'https://github.com/aws/aws-tools-for-powershell'
            IconUri = 'https://sdk-for-net.amazonwebservices.com/images/AWSLogo128x128.png'
            ReleaseNotes = 'https://github.com/aws/aws-tools-for-powershell/blob/master/CHANGELOG.md'
        }
    }
}
