version: 0.2
env:
  shell: bash
phases:

  install:
    runtime-versions:
      dotnet: 8.0

  pre_build:
    commands:
      - dotnet --info
      - pwsh -NonInteractive -NoProfile -Command '$PSVersionTable'

  build:
    commands:
      # PatchNumber must be the highest possible 5.0.x.x value so the release notes generator compares against the latest 5.0 PSGallery release
      - dotnet msbuild buildtools/build.proj /t:full-build /p:RunTests=false /p:PatchNumber=5.0.65534.0

artifacts:
  files:
    - BreakingChangesLookup.xml
  name: artifact-$(date -u +%Y-%m-%d-T%H-%M-Z).zip
