/*******************************************************************************
 *  Copyright 2012-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *  Licensed under the Apache License, Version 2.0 (the "License"). You may not use
 *  this file except in compliance with the License. A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 *  or in the "license" file accompanying this file.
 *  This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 *  CONDITIONS OF ANY KIND, either express or implied. See the License for the
 *  specific language governing permissions and limitations under the License.
 * *****************************************************************************
 *
 *  AWS Tools for Windows (TM) PowerShell (TM)
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Management.Automation;
using System.Text;
using Amazon.PowerShell.Common;
using Amazon.Runtime;
using Amazon.Inspector;
using Amazon.Inspector.Model;

namespace Amazon.PowerShell.Cmdlets.INS
{
    /// <summary>
    /// Lists findings generated by the assessment run specified by the run ARNs.
    /// </summary>
    [Cmdlet("Get", "INSFindingList")]
    [OutputType("System.String")]
    [AWSCmdlet("Invokes the ListFindings operation against Amazon Inspector.", Operation = new[] {"ListFindings"})]
    [AWSCmdletOutput("System.String",
        "This cmdlet returns a collection of String objects.",
        "The service call response (type ListFindingsResponse) can also be referenced from properties attached to the cmdlet entry in the $AWSHistory stack.",
        "Additionally, the following properties are added as Note properties to the service response type instance for the cmdlet entry in the $AWSHistory stack: NextToken (type String)"
    )]
    public class GetINSFindingListCmdlet : AmazonInspectorClientCmdlet, IExecutor
    {
        /// <summary>
        /// <para>
        /// <para>For a record to match a filter, the value specified for this data type property must
        /// be the exact match of the value of the <b>attributes</b> property of the <a>Finding</a>
        /// data type.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter]
        [Alias("Filter_Attributes")]
        public Amazon.Inspector.Model.Attribute[] Filter_Attribute { get; set; }
        
        /// <summary>
        /// <para>
        /// <para>For a record to match a filter, the value specified for this data type property must
        /// be the exact match of the value of the <b>ruleName</b> property of the <a>Finding</a>
        /// data type.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter]
        [Alias("Filter_RuleNames")]
        public System.String[] Filter_RuleName { get; set; }
        
        /// <summary>
        /// <para>
        /// <para>For a record to match a filter, the value specified for this data type property must
        /// be the exact match of the value of the <b>rulesPackageArn</b> property of the <a>Finding</a>
        /// data type.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter]
        [Alias("Filter_RulesPackageArns")]
        public System.String[] Filter_RulesPackageArn { get; set; }
        
        /// <summary>
        /// <para>
        /// <para>The ARNs of the assessment runs that generate the findings that you want to list.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(Position = 0, ValueFromPipeline = true)]
        [Alias("RunArns")]
        public System.String[] RunArn { get; set; }
        
        /// <summary>
        /// <para>
        /// <para>For a record to match a filter, the value specified for this data type property must
        /// be the exact match of the value of the <b>severity</b> property of the <a>Finding</a>
        /// data type.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter]
        [Alias("Filter_Severities")]
        public System.String[] Filter_Severity { get; set; }
        
        /// <summary>
        /// <para>
        /// <para>For a record to match a filter, the value specified for this data type property must
        /// be the exact match of the value of the <b>userAttributes</b> property of the <a>Finding</a>
        /// data type.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter]
        [Alias("Filter_UserAttributes")]
        public Amazon.Inspector.Model.Attribute[] Filter_UserAttribute { get; set; }
        
        /// <summary>
        /// <para>
        /// <para>You can use this parameter to indicate the maximum number of items you want in the
        /// response. The default value is 10. The maximum value is 500.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter]
        [Alias("MaxItems","MaxResults")]
        public int MaxResult { get; set; }
        
        /// <summary>
        /// <para>
        /// <para>You can use this parameter when paginating results. Set the value of this parameter
        /// to 'null' on your first call to the <b>ListFindings</b> action. Subsequent calls to
        /// the action fill <b>nextToken</b> in the request with the value of <b>NextToken</b>
        /// from previous response to continue listing data.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter]
        public String NextToken { get; set; }
        
        
        protected override void ProcessRecord()
        {
            base.ProcessRecord();
            
            var context = new CmdletContext
            {
                Region = this.Region,
                Credentials = this.CurrentCredentials
            };
            
            if (this.Filter_Attribute != null)
            {
                context.Filter_Attributes = new List<Amazon.Inspector.Model.Attribute>(this.Filter_Attribute);
            }
            if (this.Filter_RuleName != null)
            {
                context.Filter_RuleNames = new List<String>(this.Filter_RuleName);
            }
            if (this.Filter_RulesPackageArn != null)
            {
                context.Filter_RulesPackageArns = new List<String>(this.Filter_RulesPackageArn);
            }
            if (this.Filter_Severity != null)
            {
                context.Filter_Severities = new List<String>(this.Filter_Severity);
            }
            if (this.Filter_UserAttribute != null)
            {
                context.Filter_UserAttributes = new List<Amazon.Inspector.Model.Attribute>(this.Filter_UserAttribute);
            }
            if (ParameterWasBound("MaxResult"))
                context.MaxResults = this.MaxResult;
            context.NextToken = this.NextToken;
            if (this.RunArn != null)
            {
                context.RunArns = new List<String>(this.RunArn);
            }
            
            var output = Execute(context) as CmdletOutput;
            ProcessOutput(output);
        }
        
        #region IExecutor Members
        
        public object Execute(ExecutorContext context)
        {
            var cmdletContext = context as CmdletContext;
            
            // create request and set iteration invariants
            var request = new ListFindingsRequest();
            
             // populate Filter
            bool requestFilterIsNull = true;
            request.Filter = new FindingsFilter();
            List<Amazon.Inspector.Model.Attribute> requestFilter_filter_Attribute = null;
            if (cmdletContext.Filter_Attributes != null)
            {
                requestFilter_filter_Attribute = cmdletContext.Filter_Attributes;
            }
            if (requestFilter_filter_Attribute != null)
            {
                request.Filter.Attributes = requestFilter_filter_Attribute;
                requestFilterIsNull = false;
            }
            List<String> requestFilter_filter_RuleName = null;
            if (cmdletContext.Filter_RuleNames != null)
            {
                requestFilter_filter_RuleName = cmdletContext.Filter_RuleNames;
            }
            if (requestFilter_filter_RuleName != null)
            {
                request.Filter.RuleNames = requestFilter_filter_RuleName;
                requestFilterIsNull = false;
            }
            List<String> requestFilter_filter_RulesPackageArn = null;
            if (cmdletContext.Filter_RulesPackageArns != null)
            {
                requestFilter_filter_RulesPackageArn = cmdletContext.Filter_RulesPackageArns;
            }
            if (requestFilter_filter_RulesPackageArn != null)
            {
                request.Filter.RulesPackageArns = requestFilter_filter_RulesPackageArn;
                requestFilterIsNull = false;
            }
            List<String> requestFilter_filter_Severity = null;
            if (cmdletContext.Filter_Severities != null)
            {
                requestFilter_filter_Severity = cmdletContext.Filter_Severities;
            }
            if (requestFilter_filter_Severity != null)
            {
                request.Filter.Severities = requestFilter_filter_Severity;
                requestFilterIsNull = false;
            }
            List<Amazon.Inspector.Model.Attribute> requestFilter_filter_UserAttribute = null;
            if (cmdletContext.Filter_UserAttributes != null)
            {
                requestFilter_filter_UserAttribute = cmdletContext.Filter_UserAttributes;
            }
            if (requestFilter_filter_UserAttribute != null)
            {
                request.Filter.UserAttributes = requestFilter_filter_UserAttribute;
                requestFilterIsNull = false;
            }
             // determine if request.Filter should be set to null
            if (requestFilterIsNull)
            {
                request.Filter = null;
            }
            if (cmdletContext.RunArns != null)
            {
                request.RunArns = cmdletContext.RunArns;
            }
            
            // Initialize loop variants and commence piping
            String _nextMarker = null;
            int? _emitLimit = null;
            int _retrievedSoFar = 0;
            if (AutoIterationHelpers.HasValue(cmdletContext.NextToken))
            {
                _nextMarker = cmdletContext.NextToken;
            }
            if (AutoIterationHelpers.HasValue(cmdletContext.MaxResults))
            {
                _emitLimit = cmdletContext.MaxResults;
            }
            bool _userControllingPaging = AutoIterationHelpers.HasValue(cmdletContext.NextToken) || AutoIterationHelpers.HasValue(cmdletContext.MaxResults);
            bool _continueIteration = true;
            
            try
            {
                do
                {
                    request.NextToken = _nextMarker;
                    if (AutoIterationHelpers.HasValue(_emitLimit))
                    {
                        request.MaxResults = AutoIterationHelpers.ConvertEmitLimitToInt32(_emitLimit.Value);
                    }
                    
                    var client = Client ?? CreateClient(context.Credentials, context.Region);
                    CmdletOutput output;
                    
                    try
                    {
                        
                        var response = client.ListFindings(request);
                        Dictionary<string, object> notes = null;
                        object pipelineOutput = response.FindingArnList;
                        notes = new Dictionary<string, object>();
                        notes["NextToken"] = response.NextToken;
                        output = new CmdletOutput
                        {
                            PipelineOutput = pipelineOutput,
                            ServiceResponse = response,
                            Notes = notes
                        };
                        int _receivedThisCall = response.FindingArnList.Count;
                        if (_userControllingPaging)
                        {
                            WriteProgressRecord("Retrieving", string.Format("Retrieved {0} records starting from marker '{1}'", _receivedThisCall, request.NextToken));
                        }
                        
                        _nextMarker = response.NextToken;
                        
                        _retrievedSoFar += _receivedThisCall;
                        if (AutoIterationHelpers.HasValue(_emitLimit) && (_retrievedSoFar == 0 || _retrievedSoFar >= _emitLimit.Value))
                        {
                            _continueIteration = false;
                        }
                    }
                    catch (Exception e)
                    {
                        output = new CmdletOutput { ErrorResponse = e };
                    }
                    
                    ProcessOutput(output);
                } while (_continueIteration && AutoIterationHelpers.HasValue(_nextMarker));
                
            }
            finally
            {
                if (_userControllingPaging)
                {
                    WriteProgressCompleteRecord("Retrieving", "Retrieved records");
                }
            }
            
            return null;
        }
        
        public ExecutorContext CreateContext()
        {
            return new CmdletContext();
        }
        
        #endregion
        
        
        internal class CmdletContext : ExecutorContext
        {
            public List<Amazon.Inspector.Model.Attribute> Filter_Attributes { get; set; }
            public List<String> Filter_RuleNames { get; set; }
            public List<String> Filter_RulesPackageArns { get; set; }
            public List<String> Filter_Severities { get; set; }
            public List<Amazon.Inspector.Model.Attribute> Filter_UserAttributes { get; set; }
            public int? MaxResults { get; set; }
            public String NextToken { get; set; }
            public List<String> RunArns { get; set; }
        }
        
    }
}
