/*******************************************************************************
 *  Copyright 2012-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *  Licensed under the Apache License, Version 2.0 (the "License"). You may not use
 *  this file except in compliance with the License. A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 *  or in the "license" file accompanying this file.
 *  This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 *  CONDITIONS OF ANY KIND, either express or implied. See the License for the
 *  specific language governing permissions and limitations under the License.
 * *****************************************************************************
 *
 *  AWS Tools for Windows (TM) PowerShell (TM)
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Management.Automation;
using System.Text;
using Amazon.PowerShell.Common;
using Amazon.Runtime;
using Amazon.Inspector;
using Amazon.Inspector.Model;

namespace Amazon.PowerShell.Cmdlets.INS
{
    /// <summary>
    /// Creates an assessment for the application specified by the application ARN. You can
    /// create up to 500 assessments per AWS account.
    /// </summary>
    [Cmdlet("New", "INSAssessment", SupportsShouldProcess = true, ConfirmImpact = ConfirmImpact.Medium)]
    [OutputType("System.String")]
    [AWSCmdlet("Invokes the CreateAssessment operation against Amazon Inspector.", Operation = new[] {"CreateAssessment"})]
    [AWSCmdletOutput("System.String",
        "This cmdlet returns a String object.",
        "The service call response (type CreateAssessmentResponse) can also be referenced from properties attached to the cmdlet entry in the $AWSHistory stack."
    )]
    public class NewINSAssessmentCmdlet : AmazonInspectorClientCmdlet, IExecutor
    {
        /// <summary>
        /// <para>
        /// <para>The ARN specifying the application for which you want to create an assessment.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(Position = 0, ValueFromPipeline = true)]
        public String ApplicationArn { get; set; }
        
        /// <summary>
        /// <para>
        /// <para>The user-defined name identifying the assessment that you want to create. You can
        /// create several assessments for an application. The names of the assessments corresponding
        /// to a particular application must be unique.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter]
        public String AssessmentName { get; set; }
        
        /// <summary>
        /// <para>
        /// <para>The duration of the assessment in seconds. The default value is 3600 seconds (one
        /// hour). The maximum value is 86400 seconds (one day).</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter]
        [Alias("DurationInSeconds")]
        public Int32 DurationInSecond { get; set; }
        
        /// <summary>
        /// <para>
        /// <para>The user-defined attributes that are assigned to every finding generated by running
        /// this assessment.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter]
        [Alias("UserAttributesForFindings")]
        public Amazon.Inspector.Model.Attribute[] UserAttributesForFinding { get; set; }
        
        /// <summary>
        /// This parameter overrides confirmation prompts to force 
        /// the cmdlet to continue its operation. This parameter should always
        /// be used with caution.
        /// </summary>
        [System.Management.Automation.Parameter]
        public SwitchParameter Force { get; set; }
        
        
        protected override void ProcessRecord()
        {
            base.ProcessRecord();
            
            var resourceIdentifiersText = FormatParameterValuesForConfirmationMsg("ApplicationArn", MyInvocation.BoundParameters);
            if (!ConfirmShouldProceed(this.Force.IsPresent, resourceIdentifiersText, "New-INSAssessment (CreateAssessment)"))
            {
                return;
            }
            
            var context = new CmdletContext
            {
                Region = this.Region,
                Credentials = this.CurrentCredentials
            };
            
            context.ApplicationArn = this.ApplicationArn;
            context.AssessmentName = this.AssessmentName;
            if (ParameterWasBound("DurationInSecond"))
                context.DurationInSeconds = this.DurationInSecond;
            if (this.UserAttributesForFinding != null)
            {
                context.UserAttributesForFindings = new List<Amazon.Inspector.Model.Attribute>(this.UserAttributesForFinding);
            }
            
            var output = Execute(context) as CmdletOutput;
            ProcessOutput(output);
        }
        
        #region IExecutor Members
        
        public object Execute(ExecutorContext context)
        {
            var cmdletContext = context as CmdletContext;
            // create request
            var request = new CreateAssessmentRequest();
            
            if (cmdletContext.ApplicationArn != null)
            {
                request.ApplicationArn = cmdletContext.ApplicationArn;
            }
            if (cmdletContext.AssessmentName != null)
            {
                request.AssessmentName = cmdletContext.AssessmentName;
            }
            if (cmdletContext.DurationInSeconds != null)
            {
                request.DurationInSeconds = cmdletContext.DurationInSeconds.Value;
            }
            if (cmdletContext.UserAttributesForFindings != null)
            {
                request.UserAttributesForFindings = cmdletContext.UserAttributesForFindings;
            }
            
            CmdletOutput output;
            
            // issue call
            var client = Client ?? CreateClient(context.Credentials, context.Region);
            try
            {
                var response = client.CreateAssessment(request);
                Dictionary<string, object> notes = null;
                object pipelineOutput = response.AssessmentArn;
                output = new CmdletOutput
                {
                    PipelineOutput = pipelineOutput,
                    ServiceResponse = response,
                    Notes = notes
                };
            }
            catch (Exception e)
            {
                output = new CmdletOutput { ErrorResponse = e };
            }
            
            return output;
        }
        
        public ExecutorContext CreateContext()
        {
            return new CmdletContext();
        }
        
        #endregion
        
        
        internal class CmdletContext : ExecutorContext
        {
            public String ApplicationArn { get; set; }
            public String AssessmentName { get; set; }
            public Int32? DurationInSeconds { get; set; }
            public List<Amazon.Inspector.Model.Attribute> UserAttributesForFindings { get; set; }
        }
        
    }
}
