/*******************************************************************************
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *  Licensed under the Apache License, Version 2.0 (the "License"). You may not use
 *  this file except in compliance with the License. A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 *  or in the "license" file accompanying this file.
 *  This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 *  CONDITIONS OF ANY KIND, either express or implied. See the License for the
 *  specific language governing permissions and limitations under the License.
 * *****************************************************************************
 *
 *  AWS Tools for Windows (TM) PowerShell (TM)
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Management.Automation;
using System.Text;
using Amazon.PowerShell.Common;
using Amazon.Runtime;
using System.Threading;
using Amazon.AppSync;
using Amazon.AppSync.Model;

#pragma warning disable CS0618, CS0612
namespace Amazon.PowerShell.Cmdlets.ASYN
{
    /// <summary>
    /// Creates an association between a Merged API and source API using the Merged API's
    /// identifier.
    /// </summary>
    [Cmdlet("Start", "ASYNSourceGraphqlApi", SupportsShouldProcess = true, ConfirmImpact = ConfirmImpact.Medium)]
    [OutputType("Amazon.AppSync.Model.SourceApiAssociation")]
    [AWSCmdlet("Calls the AWS AppSync AssociateSourceGraphqlApi API operation.", Operation = new[] {"AssociateSourceGraphqlApi"}, SelectReturnType = typeof(Amazon.AppSync.Model.AssociateSourceGraphqlApiResponse))]
    [AWSCmdletOutput("Amazon.AppSync.Model.SourceApiAssociation or Amazon.AppSync.Model.AssociateSourceGraphqlApiResponse",
        "This cmdlet returns an Amazon.AppSync.Model.SourceApiAssociation object.",
        "The service call response (type Amazon.AppSync.Model.AssociateSourceGraphqlApiResponse) can be returned by specifying '-Select *'."
    )]
    public partial class StartASYNSourceGraphqlApiCmdlet : AmazonAppSyncClientCmdlet, IExecutor
    {
        
        protected override bool IsGeneratedCmdlet { get; set; } = true;
        private readonly CancellationTokenSource _cancellationTokenSource = new CancellationTokenSource();
        
        #region Parameter Description
        /// <summary>
        /// <para>
        /// <para>The description field.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        public System.String Description { get; set; }
        #endregion
        
        #region Parameter MergedApiIdentifier
        /// <summary>
        /// <para>
        /// <para>The identifier of the AppSync Merged API. This is generated by the AppSync service.
        /// In most cases, Merged APIs (especially in your account) only require the API ID value
        /// or ARN of the merged API. However, Merged APIs in other accounts (cross-account use
        /// cases) strictly require the full resource ARN of the merged API.</para>
        /// </para>
        /// </summary>
        #if !MODULAR
        [System.Management.Automation.Parameter(Position = 0, ValueFromPipelineByPropertyName = true, ValueFromPipeline = true)]
        #else
        [System.Management.Automation.Parameter(Position = 0, ValueFromPipelineByPropertyName = true, ValueFromPipeline = true, Mandatory = true)]
        [System.Management.Automation.AllowEmptyString]
        [System.Management.Automation.AllowNull]
        #endif
        [Amazon.PowerShell.Common.AWSRequiredParameter]
        public System.String MergedApiIdentifier { get; set; }
        #endregion
        
        #region Parameter SourceApiAssociationConfig_MergeType
        /// <summary>
        /// <para>
        /// <para>The property that indicates which merging option is enabled in the source API association.</para><para>Valid merge types are <c>MANUAL_MERGE</c> (default) and <c>AUTO_MERGE</c>. Manual
        /// merges are the default behavior and require the user to trigger any changes from the
        /// source APIs to the merged API manually. Auto merges subscribe the merged API to the
        /// changes performed on the source APIs so that any change in the source APIs are also
        /// made to the merged API. Auto merges use <c>MergedApiExecutionRoleArn</c> to perform
        /// merge operations.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        [AWSConstantClassSource("Amazon.AppSync.MergeType")]
        public Amazon.AppSync.MergeType SourceApiAssociationConfig_MergeType { get; set; }
        #endregion
        
        #region Parameter SourceApiIdentifier
        /// <summary>
        /// <para>
        /// <para>The identifier of the AppSync Source API. This is generated by the AppSync service.
        /// In most cases, source APIs (especially in your account) only require the API ID value
        /// or ARN of the source API. However, source APIs from other accounts (cross-account
        /// use cases) strictly require the full resource ARN of the source API.</para>
        /// </para>
        /// </summary>
        #if !MODULAR
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        #else
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true, Mandatory = true)]
        [System.Management.Automation.AllowEmptyString]
        [System.Management.Automation.AllowNull]
        #endif
        [Amazon.PowerShell.Common.AWSRequiredParameter]
        public System.String SourceApiIdentifier { get; set; }
        #endregion
        
        #region Parameter Select
        /// <summary>
        /// Use the -Select parameter to control the cmdlet output. The default value is 'SourceApiAssociation'.
        /// Specifying -Select '*' will result in the cmdlet returning the whole service response (Amazon.AppSync.Model.AssociateSourceGraphqlApiResponse).
        /// Specifying the name of a property of type Amazon.AppSync.Model.AssociateSourceGraphqlApiResponse will result in that property being returned.
        /// Specifying -Select '^ParameterName' will result in the cmdlet returning the selected cmdlet parameter value.
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        public string Select { get; set; } = "SourceApiAssociation";
        #endregion
        
        #region Parameter Force
        /// <summary>
        /// This parameter overrides confirmation prompts to force 
        /// the cmdlet to continue its operation. This parameter should always
        /// be used with caution.
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        public SwitchParameter Force { get; set; }
        #endregion
        
        protected override void StopProcessing()
        {
            base.StopProcessing();
            _cancellationTokenSource.Cancel();
        }
        protected override void ProcessRecord()
        {
            base.ProcessRecord();
            
            var resourceIdentifiersText = FormatParameterValuesForConfirmationMsg(nameof(this.MergedApiIdentifier), MyInvocation.BoundParameters);
            if (!ConfirmShouldProceed(this.Force.IsPresent, resourceIdentifiersText, "Start-ASYNSourceGraphqlApi (AssociateSourceGraphqlApi)"))
            {
                return;
            }
            
            var context = new CmdletContext();
            
            // allow for manipulation of parameters prior to loading into context
            PreExecutionContextLoad(context);
            
            if (ParameterWasBound(nameof(this.Select)))
            {
                context.Select = CreateSelectDelegate<Amazon.AppSync.Model.AssociateSourceGraphqlApiResponse, StartASYNSourceGraphqlApiCmdlet>(Select) ??
                    throw new System.ArgumentException("Invalid value for -Select parameter.", nameof(this.Select));
            }
            context.Description = this.Description;
            context.MergedApiIdentifier = this.MergedApiIdentifier;
            #if MODULAR
            if (this.MergedApiIdentifier == null && ParameterWasBound(nameof(this.MergedApiIdentifier)))
            {
                WriteWarning("You are passing $null as a value for parameter MergedApiIdentifier which is marked as required. In case you believe this parameter was incorrectly marked as required, report this by opening an issue at https://github.com/aws/aws-tools-for-powershell/issues.");
            }
            #endif
            context.SourceApiAssociationConfig_MergeType = this.SourceApiAssociationConfig_MergeType;
            context.SourceApiIdentifier = this.SourceApiIdentifier;
            #if MODULAR
            if (this.SourceApiIdentifier == null && ParameterWasBound(nameof(this.SourceApiIdentifier)))
            {
                WriteWarning("You are passing $null as a value for parameter SourceApiIdentifier which is marked as required. In case you believe this parameter was incorrectly marked as required, report this by opening an issue at https://github.com/aws/aws-tools-for-powershell/issues.");
            }
            #endif
            
            // allow further manipulation of loaded context prior to processing
            PostExecutionContextLoad(context);
            
            var output = Execute(context) as CmdletOutput;
            ProcessOutput(output);
        }
        
        #region IExecutor Members
        
        public object Execute(ExecutorContext context)
        {
            var cmdletContext = context as CmdletContext;
            // create request
            var request = new Amazon.AppSync.Model.AssociateSourceGraphqlApiRequest();
            
            if (cmdletContext.Description != null)
            {
                request.Description = cmdletContext.Description;
            }
            if (cmdletContext.MergedApiIdentifier != null)
            {
                request.MergedApiIdentifier = cmdletContext.MergedApiIdentifier;
            }
            
             // populate SourceApiAssociationConfig
            var requestSourceApiAssociationConfigIsNull = true;
            request.SourceApiAssociationConfig = new Amazon.AppSync.Model.SourceApiAssociationConfig();
            Amazon.AppSync.MergeType requestSourceApiAssociationConfig_sourceApiAssociationConfig_MergeType = null;
            if (cmdletContext.SourceApiAssociationConfig_MergeType != null)
            {
                requestSourceApiAssociationConfig_sourceApiAssociationConfig_MergeType = cmdletContext.SourceApiAssociationConfig_MergeType;
            }
            if (requestSourceApiAssociationConfig_sourceApiAssociationConfig_MergeType != null)
            {
                request.SourceApiAssociationConfig.MergeType = requestSourceApiAssociationConfig_sourceApiAssociationConfig_MergeType;
                requestSourceApiAssociationConfigIsNull = false;
            }
             // determine if request.SourceApiAssociationConfig should be set to null
            if (requestSourceApiAssociationConfigIsNull)
            {
                request.SourceApiAssociationConfig = null;
            }
            if (cmdletContext.SourceApiIdentifier != null)
            {
                request.SourceApiIdentifier = cmdletContext.SourceApiIdentifier;
            }
            
            CmdletOutput output;
            
            // issue call
            var client = Client ?? CreateClient(_CurrentCredentials, _RegionEndpoint);
            try
            {
                var response = CallAWSServiceOperation(client, request);
                object pipelineOutput = null;
                pipelineOutput = cmdletContext.Select(response, this);
                output = new CmdletOutput
                {
                    PipelineOutput = pipelineOutput,
                    ServiceResponse = response
                };
            }
            catch (Exception e)
            {
                output = new CmdletOutput { ErrorResponse = e };
            }
            
            return output;
        }
        
        public ExecutorContext CreateContext()
        {
            return new CmdletContext();
        }
        
        #endregion
        
        #region AWS Service Operation Call
        
        private Amazon.AppSync.Model.AssociateSourceGraphqlApiResponse CallAWSServiceOperation(IAmazonAppSync client, Amazon.AppSync.Model.AssociateSourceGraphqlApiRequest request)
        {
            Utils.Common.WriteVerboseEndpointMessage(this, client.Config, "AWS AppSync", "AssociateSourceGraphqlApi");
            try
            {
                return client.AssociateSourceGraphqlApiAsync(request, _cancellationTokenSource.Token).GetAwaiter().GetResult();
            }
            catch (AmazonServiceException exc)
            {
                var webException = exc.InnerException as System.Net.WebException;
                if (webException != null)
                {
                    throw new Exception(Utils.Common.FormatNameResolutionFailureMessage(client.Config, webException.Message), webException);
                }
                throw;
            }
        }
        
        #endregion
        
        internal partial class CmdletContext : ExecutorContext
        {
            public System.String Description { get; set; }
            public System.String MergedApiIdentifier { get; set; }
            public Amazon.AppSync.MergeType SourceApiAssociationConfig_MergeType { get; set; }
            public System.String SourceApiIdentifier { get; set; }
            public System.Func<Amazon.AppSync.Model.AssociateSourceGraphqlApiResponse, StartASYNSourceGraphqlApiCmdlet, object> Select { get; set; } =
                (response, cmdlet) => response.SourceApiAssociation;
        }
        
    }
}
