/*******************************************************************************
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *  Licensed under the Apache License, Version 2.0 (the "License"). You may not use
 *  this file except in compliance with the License. A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 *  or in the "license" file accompanying this file.
 *  This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 *  CONDITIONS OF ANY KIND, either express or implied. See the License for the
 *  specific language governing permissions and limitations under the License.
 * *****************************************************************************
 *
 *  AWS Tools for Windows (TM) PowerShell (TM)
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Management.Automation;
using System.Text;
using Amazon.PowerShell.Common;
using Amazon.Runtime;
using System.Threading;
using Amazon.GroundStation;
using Amazon.GroundStation.Model;

#pragma warning disable CS0618, CS0612
namespace Amazon.PowerShell.Cmdlets.GS
{
    /// <summary>
    /// Updates a specific contact.
    /// </summary>
    [Cmdlet("Update", "GSContact", SupportsShouldProcess = true, ConfirmImpact = ConfirmImpact.Medium)]
    [OutputType("Amazon.GroundStation.Model.UpdateContactResponse")]
    [AWSCmdlet("Calls the AWS Ground Station UpdateContact API operation.", Operation = new[] {"UpdateContact"}, SelectReturnType = typeof(Amazon.GroundStation.Model.UpdateContactResponse))]
    [AWSCmdletOutput("Amazon.GroundStation.Model.UpdateContactResponse",
        "This cmdlet returns an Amazon.GroundStation.Model.UpdateContactResponse object containing multiple properties."
    )]
    public partial class UpdateGSContactCmdlet : AmazonGroundStationClientCmdlet, IExecutor
    {
        
        protected override bool IsGeneratedCmdlet { get; set; } = true;
        private readonly CancellationTokenSource _cancellationTokenSource = new CancellationTokenSource();
        
        #region Parameter ContactId
        /// <summary>
        /// <para>
        /// <para>UUID of a contact.</para>
        /// </para>
        /// </summary>
        #if !MODULAR
        [System.Management.Automation.Parameter(Position = 0, ValueFromPipelineByPropertyName = true, ValueFromPipeline = true)]
        #else
        [System.Management.Automation.Parameter(Position = 0, ValueFromPipelineByPropertyName = true, ValueFromPipeline = true, Mandatory = true)]
        [System.Management.Automation.AllowEmptyString]
        [System.Management.Automation.AllowNull]
        #endif
        [Amazon.PowerShell.Common.AWSRequiredParameter]
        public System.String ContactId { get; set; }
        #endregion
        
        #region Parameter TrackingOverrides_ProgramTrackSettings_AzEl_EphemerisId
        /// <summary>
        /// <para>
        /// <para>Unique identifier of the azimuth elevation ephemeris.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        public System.String TrackingOverrides_ProgramTrackSettings_AzEl_EphemerisId { get; set; }
        #endregion
        
        #region Parameter TrackingOverrides_ProgramTrackSettings_Oem_EphemerisId
        /// <summary>
        /// <para>
        /// <para>Unique identifier of the OEM ephemeris.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        public System.String TrackingOverrides_ProgramTrackSettings_Oem_EphemerisId { get; set; }
        #endregion
        
        #region Parameter TrackingOverrides_ProgramTrackSettings_Tle_EphemerisId
        /// <summary>
        /// <para>
        /// <para>Unique identifier of the TLE ephemeris.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        public System.String TrackingOverrides_ProgramTrackSettings_Tle_EphemerisId { get; set; }
        #endregion
        
        #region Parameter SatelliteArn
        /// <summary>
        /// <para>
        /// <para>ARN of a satellite.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        public System.String SatelliteArn { get; set; }
        #endregion
        
        #region Parameter ClientToken
        /// <summary>
        /// <para>
        /// <para>A client token is a unique, case-sensitive string of up to 64 ASCII characters. It
        /// is generated by the client to ensure idempotent operations, allowing safe retries
        /// without unintended side effects.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        public System.String ClientToken { get; set; }
        #endregion
        
        #region Parameter Select
        /// <summary>
        /// Use the -Select parameter to control the cmdlet output. The default value is '*'.
        /// Specifying -Select '*' will result in the cmdlet returning the whole service response (Amazon.GroundStation.Model.UpdateContactResponse).
        /// Specifying the name of a property of type Amazon.GroundStation.Model.UpdateContactResponse will result in that property being returned.
        /// Specifying -Select '^ParameterName' will result in the cmdlet returning the selected cmdlet parameter value.
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        public string Select { get; set; } = "*";
        #endregion
        
        #region Parameter Force
        /// <summary>
        /// This parameter overrides confirmation prompts to force 
        /// the cmdlet to continue its operation. This parameter should always
        /// be used with caution.
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        public SwitchParameter Force { get; set; }
        #endregion
        
        protected override void StopProcessing()
        {
            base.StopProcessing();
            _cancellationTokenSource.Cancel();
        }
        protected override void ProcessRecord()
        {
            base.ProcessRecord();
            
            var resourceIdentifiersText = FormatParameterValuesForConfirmationMsg(nameof(this.ContactId), MyInvocation.BoundParameters);
            if (!ConfirmShouldProceed(this.Force.IsPresent, resourceIdentifiersText, "Update-GSContact (UpdateContact)"))
            {
                return;
            }
            
            var context = new CmdletContext();
            
            // allow for manipulation of parameters prior to loading into context
            PreExecutionContextLoad(context);
            
            if (ParameterWasBound(nameof(this.Select)))
            {
                context.Select = CreateSelectDelegate<Amazon.GroundStation.Model.UpdateContactResponse, UpdateGSContactCmdlet>(Select) ??
                    throw new System.ArgumentException("Invalid value for -Select parameter.", nameof(this.Select));
            }
            context.ClientToken = this.ClientToken;
            context.ContactId = this.ContactId;
            #if MODULAR
            if (this.ContactId == null && ParameterWasBound(nameof(this.ContactId)))
            {
                WriteWarning("You are passing $null as a value for parameter ContactId which is marked as required. In case you believe this parameter was incorrectly marked as required, report this by opening an issue at https://github.com/aws/aws-tools-for-powershell/issues.");
            }
            #endif
            context.SatelliteArn = this.SatelliteArn;
            context.TrackingOverrides_ProgramTrackSettings_AzEl_EphemerisId = this.TrackingOverrides_ProgramTrackSettings_AzEl_EphemerisId;
            context.TrackingOverrides_ProgramTrackSettings_Oem_EphemerisId = this.TrackingOverrides_ProgramTrackSettings_Oem_EphemerisId;
            context.TrackingOverrides_ProgramTrackSettings_Tle_EphemerisId = this.TrackingOverrides_ProgramTrackSettings_Tle_EphemerisId;
            
            // allow further manipulation of loaded context prior to processing
            PostExecutionContextLoad(context);
            
            var output = Execute(context) as CmdletOutput;
            ProcessOutput(output);
        }
        
        #region IExecutor Members
        
        public object Execute(ExecutorContext context)
        {
            var cmdletContext = context as CmdletContext;
            // create request
            var request = new Amazon.GroundStation.Model.UpdateContactRequest();
            
            if (cmdletContext.ClientToken != null)
            {
                request.ClientToken = cmdletContext.ClientToken;
            }
            if (cmdletContext.ContactId != null)
            {
                request.ContactId = cmdletContext.ContactId;
            }
            if (cmdletContext.SatelliteArn != null)
            {
                request.SatelliteArn = cmdletContext.SatelliteArn;
            }
            
             // populate TrackingOverrides
            var requestTrackingOverridesIsNull = true;
            request.TrackingOverrides = new Amazon.GroundStation.Model.TrackingOverrides();
            Amazon.GroundStation.Model.ProgramTrackSettings requestTrackingOverrides_trackingOverrides_ProgramTrackSettings = null;
            
             // populate ProgramTrackSettings
            var requestTrackingOverrides_trackingOverrides_ProgramTrackSettingsIsNull = true;
            requestTrackingOverrides_trackingOverrides_ProgramTrackSettings = new Amazon.GroundStation.Model.ProgramTrackSettings();
            Amazon.GroundStation.Model.AzElProgramTrackSettings requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_AzEl = null;
            
             // populate AzEl
            var requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_AzElIsNull = true;
            requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_AzEl = new Amazon.GroundStation.Model.AzElProgramTrackSettings();
            System.String requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_AzEl_trackingOverrides_ProgramTrackSettings_AzEl_EphemerisId = null;
            if (cmdletContext.TrackingOverrides_ProgramTrackSettings_AzEl_EphemerisId != null)
            {
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_AzEl_trackingOverrides_ProgramTrackSettings_AzEl_EphemerisId = cmdletContext.TrackingOverrides_ProgramTrackSettings_AzEl_EphemerisId;
            }
            if (requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_AzEl_trackingOverrides_ProgramTrackSettings_AzEl_EphemerisId != null)
            {
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_AzEl.EphemerisId = requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_AzEl_trackingOverrides_ProgramTrackSettings_AzEl_EphemerisId;
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_AzElIsNull = false;
            }
             // determine if requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_AzEl should be set to null
            if (requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_AzElIsNull)
            {
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_AzEl = null;
            }
            if (requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_AzEl != null)
            {
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettings.AzEl = requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_AzEl;
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettingsIsNull = false;
            }
            Amazon.GroundStation.Model.OemProgramTrackSettings requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Oem = null;
            
             // populate Oem
            var requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_OemIsNull = true;
            requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Oem = new Amazon.GroundStation.Model.OemProgramTrackSettings();
            System.String requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Oem_trackingOverrides_ProgramTrackSettings_Oem_EphemerisId = null;
            if (cmdletContext.TrackingOverrides_ProgramTrackSettings_Oem_EphemerisId != null)
            {
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Oem_trackingOverrides_ProgramTrackSettings_Oem_EphemerisId = cmdletContext.TrackingOverrides_ProgramTrackSettings_Oem_EphemerisId;
            }
            if (requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Oem_trackingOverrides_ProgramTrackSettings_Oem_EphemerisId != null)
            {
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Oem.EphemerisId = requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Oem_trackingOverrides_ProgramTrackSettings_Oem_EphemerisId;
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_OemIsNull = false;
            }
             // determine if requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Oem should be set to null
            if (requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_OemIsNull)
            {
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Oem = null;
            }
            if (requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Oem != null)
            {
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettings.Oem = requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Oem;
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettingsIsNull = false;
            }
            Amazon.GroundStation.Model.TleProgramTrackSettings requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Tle = null;
            
             // populate Tle
            var requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_TleIsNull = true;
            requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Tle = new Amazon.GroundStation.Model.TleProgramTrackSettings();
            System.String requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Tle_trackingOverrides_ProgramTrackSettings_Tle_EphemerisId = null;
            if (cmdletContext.TrackingOverrides_ProgramTrackSettings_Tle_EphemerisId != null)
            {
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Tle_trackingOverrides_ProgramTrackSettings_Tle_EphemerisId = cmdletContext.TrackingOverrides_ProgramTrackSettings_Tle_EphemerisId;
            }
            if (requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Tle_trackingOverrides_ProgramTrackSettings_Tle_EphemerisId != null)
            {
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Tle.EphemerisId = requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Tle_trackingOverrides_ProgramTrackSettings_Tle_EphemerisId;
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_TleIsNull = false;
            }
             // determine if requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Tle should be set to null
            if (requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_TleIsNull)
            {
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Tle = null;
            }
            if (requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Tle != null)
            {
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettings.Tle = requestTrackingOverrides_trackingOverrides_ProgramTrackSettings_trackingOverrides_ProgramTrackSettings_Tle;
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettingsIsNull = false;
            }
             // determine if requestTrackingOverrides_trackingOverrides_ProgramTrackSettings should be set to null
            if (requestTrackingOverrides_trackingOverrides_ProgramTrackSettingsIsNull)
            {
                requestTrackingOverrides_trackingOverrides_ProgramTrackSettings = null;
            }
            if (requestTrackingOverrides_trackingOverrides_ProgramTrackSettings != null)
            {
                request.TrackingOverrides.ProgramTrackSettings = requestTrackingOverrides_trackingOverrides_ProgramTrackSettings;
                requestTrackingOverridesIsNull = false;
            }
             // determine if request.TrackingOverrides should be set to null
            if (requestTrackingOverridesIsNull)
            {
                request.TrackingOverrides = null;
            }
            
            CmdletOutput output;
            
            // issue call
            var client = Client ?? CreateClient(_CurrentCredentials, _RegionEndpoint);
            try
            {
                var response = CallAWSServiceOperation(client, request);
                object pipelineOutput = null;
                pipelineOutput = cmdletContext.Select(response, this);
                output = new CmdletOutput
                {
                    PipelineOutput = pipelineOutput,
                    ServiceResponse = response
                };
            }
            catch (Exception e)
            {
                output = new CmdletOutput { ErrorResponse = e };
            }
            
            return output;
        }
        
        public ExecutorContext CreateContext()
        {
            return new CmdletContext();
        }
        
        #endregion
        
        #region AWS Service Operation Call
        
        private Amazon.GroundStation.Model.UpdateContactResponse CallAWSServiceOperation(IAmazonGroundStation client, Amazon.GroundStation.Model.UpdateContactRequest request)
        {
            Utils.Common.WriteVerboseEndpointMessage(this, client.Config, "AWS Ground Station", "UpdateContact");
            try
            {
                return client.UpdateContactAsync(request, _cancellationTokenSource.Token).GetAwaiter().GetResult();
            }
            catch (AmazonServiceException exc)
            {
                var webException = exc.InnerException as System.Net.WebException;
                if (webException != null)
                {
                    throw new Exception(Utils.Common.FormatNameResolutionFailureMessage(client.Config, webException.Message), webException);
                }
                throw;
            }
        }
        
        #endregion
        
        internal partial class CmdletContext : ExecutorContext
        {
            public System.String ClientToken { get; set; }
            public System.String ContactId { get; set; }
            public System.String SatelliteArn { get; set; }
            public System.String TrackingOverrides_ProgramTrackSettings_AzEl_EphemerisId { get; set; }
            public System.String TrackingOverrides_ProgramTrackSettings_Oem_EphemerisId { get; set; }
            public System.String TrackingOverrides_ProgramTrackSettings_Tle_EphemerisId { get; set; }
            public System.Func<Amazon.GroundStation.Model.UpdateContactResponse, UpdateGSContactCmdlet, object> Select { get; set; } =
                (response, cmdlet) => response;
        }
        
    }
}
