/*******************************************************************************
 *  Copyright 2012-2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *  Licensed under the Apache License, Version 2.0 (the "License"). You may not use
 *  this file except in compliance with the License. A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 *  or in the "license" file accompanying this file.
 *  This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 *  CONDITIONS OF ANY KIND, either express or implied. See the License for the
 *  specific language governing permissions and limitations under the License.
 * *****************************************************************************
 *
 *  AWS Tools for Windows (TM) PowerShell (TM)
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Management.Automation;
using System.Text;
using Amazon.PowerShell.Common;
using Amazon.Runtime;
using Amazon.PaymentCryptographyData;
using Amazon.PaymentCryptographyData.Model;

namespace Amazon.PowerShell.Cmdlets.PAYCD
{
    /// <summary>
    /// Re-encrypt ciphertext using DUKPT, Symmetric and Asymmetric Data Encryption Keys.
    /// 
    /// 
    ///  
    /// <para>
    /// You can either generate an encryption key within Amazon Web Services Payment Cryptography
    /// by calling <a href="https://docs.aws.amazon.com/payment-cryptography/latest/APIReference/API_CreateKey.html">CreateKey</a>
    /// or import your own encryption key by calling <a href="https://docs.aws.amazon.com/payment-cryptography/latest/APIReference/API_ImportKey.html">ImportKey</a>.
    /// The <code>KeyArn</code> for use with this operation must be in a compatible key state
    /// with <code>KeyModesOfUse</code> set to <code>Encrypt</code>. In asymmetric encryption,
    /// ciphertext is encrypted using public component (imported by calling <a href="https://docs.aws.amazon.com/payment-cryptography/latest/APIReference/API_ImportKey.html">ImportKey</a>)
    /// of the asymmetric key pair created outside of Amazon Web Services Payment Cryptography.
    /// 
    /// </para><para>
    /// For symmetric and DUKPT encryption, Amazon Web Services Payment Cryptography supports
    /// <code>TDES</code> and <code>AES</code> algorithms. For asymmetric encryption, Amazon
    /// Web Services Payment Cryptography supports <code>RSA</code>. To encrypt using DUKPT,
    /// a DUKPT key must already exist within your account with <code>KeyModesOfUse</code>
    /// set to <code>DeriveKey</code> or a new DUKPT can be generated by calling <a href="https://docs.aws.amazon.com/payment-cryptography/latest/APIReference/API_CreateKey.html">CreateKey</a>.
    /// </para><para>
    /// For information about valid keys for this operation, see <a href="https://docs.aws.amazon.com/payment-cryptography/latest/userguide/keys-validattributes.html">Understanding
    /// key attributes</a> and <a href="https://docs.aws.amazon.com/payment-cryptography/latest/userguide/crypto-ops-validkeys-ops.html">Key
    /// types for specific data operations</a> in the <i>Amazon Web Services Payment Cryptography
    /// User Guide</i>. 
    /// </para><para><b>Cross-account use</b>: This operation can't be used across different Amazon Web
    /// Services accounts.
    /// </para><para><b>Related operations:</b></para><ul><li><para><a>DecryptData</a></para></li><li><para><a>EncryptData</a></para></li><li><para><a href="https://docs.aws.amazon.com/payment-cryptography/latest/APIReference/API_GetPublicKeyCertificate.html">GetPublicCertificate</a></para></li><li><para><a href="https://docs.aws.amazon.com/payment-cryptography/latest/APIReference/API_ImportKey.html">ImportKey</a></para></li></ul>
    /// </summary>
    [Cmdlet("Update", "PAYCDEncryptData", SupportsShouldProcess = true, ConfirmImpact = ConfirmImpact.Medium)]
    [OutputType("Amazon.PaymentCryptographyData.Model.ReEncryptDataResponse")]
    [AWSCmdlet("Calls the Payment Cryptography Data ReEncryptData API operation.", Operation = new[] {"ReEncryptData"}, SelectReturnType = typeof(Amazon.PaymentCryptographyData.Model.ReEncryptDataResponse))]
    [AWSCmdletOutput("Amazon.PaymentCryptographyData.Model.ReEncryptDataResponse",
        "This cmdlet returns an Amazon.PaymentCryptographyData.Model.ReEncryptDataResponse object containing multiple properties. The object can also be referenced from properties attached to the cmdlet entry in the $AWSHistory stack."
    )]
    public partial class UpdatePAYCDEncryptDataCmdlet : AmazonPaymentCryptographyDataClientCmdlet, IExecutor
    {
        
        protected override bool IsSensitiveRequest { get; set; } = true;
        
        protected override bool IsSensitiveResponse { get; set; } = true;
        
        protected override bool IsGeneratedCmdlet { get; set; } = true;
        
        #region Parameter CipherText
        /// <summary>
        /// <para>
        /// <para>Ciphertext to be encrypted. The minimum allowed length is 16 bytes and maximum allowed
        /// length is 4096 bytes.</para>
        /// </para>
        /// </summary>
        #if !MODULAR
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        #else
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true, Mandatory = true)]
        [System.Management.Automation.AllowEmptyString]
        [System.Management.Automation.AllowNull]
        #endif
        [Amazon.PowerShell.Common.AWSRequiredParameter]
        public System.String CipherText { get; set; }
        #endregion
        
        #region Parameter IncomingEncryptionAttributes_Dukpt_DukptKeyDerivationType
        /// <summary>
        /// <para>
        /// <para>The key type encrypted using DUKPT from a Base Derivation Key (BDK) and Key Serial
        /// Number (KSN). This must be less than or equal to the strength of the BDK. For example,
        /// you can't use <code>AES_128</code> as a derivation type for a BDK of <code>AES_128</code>
        /// or <code>TDES_2KEY</code></para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        [AWSConstantClassSource("Amazon.PaymentCryptographyData.DukptDerivationType")]
        public Amazon.PaymentCryptographyData.DukptDerivationType IncomingEncryptionAttributes_Dukpt_DukptKeyDerivationType { get; set; }
        #endregion
        
        #region Parameter OutgoingEncryptionAttributes_Dukpt_DukptKeyDerivationType
        /// <summary>
        /// <para>
        /// <para>The key type encrypted using DUKPT from a Base Derivation Key (BDK) and Key Serial
        /// Number (KSN). This must be less than or equal to the strength of the BDK. For example,
        /// you can't use <code>AES_128</code> as a derivation type for a BDK of <code>AES_128</code>
        /// or <code>TDES_2KEY</code></para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        [AWSConstantClassSource("Amazon.PaymentCryptographyData.DukptDerivationType")]
        public Amazon.PaymentCryptographyData.DukptDerivationType OutgoingEncryptionAttributes_Dukpt_DukptKeyDerivationType { get; set; }
        #endregion
        
        #region Parameter IncomingEncryptionAttributes_Dukpt_DukptKeyVariant
        /// <summary>
        /// <para>
        /// <para>The type of use of DUKPT, which can be incoming data decryption, outgoing data encryption,
        /// or both.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        [AWSConstantClassSource("Amazon.PaymentCryptographyData.DukptKeyVariant")]
        public Amazon.PaymentCryptographyData.DukptKeyVariant IncomingEncryptionAttributes_Dukpt_DukptKeyVariant { get; set; }
        #endregion
        
        #region Parameter OutgoingEncryptionAttributes_Dukpt_DukptKeyVariant
        /// <summary>
        /// <para>
        /// <para>The type of use of DUKPT, which can be incoming data decryption, outgoing data encryption,
        /// or both.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        [AWSConstantClassSource("Amazon.PaymentCryptographyData.DukptKeyVariant")]
        public Amazon.PaymentCryptographyData.DukptKeyVariant OutgoingEncryptionAttributes_Dukpt_DukptKeyVariant { get; set; }
        #endregion
        
        #region Parameter IncomingKeyIdentifier
        /// <summary>
        /// <para>
        /// <para>The <code>keyARN</code> of the encryption key of incoming ciphertext data.</para>
        /// </para>
        /// </summary>
        #if !MODULAR
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        #else
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true, Mandatory = true)]
        [System.Management.Automation.AllowEmptyString]
        [System.Management.Automation.AllowNull]
        #endif
        [Amazon.PowerShell.Common.AWSRequiredParameter]
        public System.String IncomingKeyIdentifier { get; set; }
        #endregion
        
        #region Parameter IncomingEncryptionAttributes_Dukpt_InitializationVector
        /// <summary>
        /// <para>
        /// <para>An input to cryptographic primitive used to provide the intial state. Typically the
        /// <code>InitializationVector</code> must have a random or psuedo-random value, but sometimes
        /// it only needs to be unpredictable or unique. If you don't provide a value, Amazon
        /// Web Services Payment Cryptography generates a random value.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        public System.String IncomingEncryptionAttributes_Dukpt_InitializationVector { get; set; }
        #endregion
        
        #region Parameter IncomingEncryptionAttributes_Symmetric_InitializationVector
        /// <summary>
        /// <para>
        /// <para>An input to cryptographic primitive used to provide the intial state. The <code>InitializationVector</code>
        /// is typically required have a random or psuedo-random value, but sometimes it only
        /// needs to be unpredictable or unique. If a value is not provided, Amazon Web Services
        /// Payment Cryptography generates a random value.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        public System.String IncomingEncryptionAttributes_Symmetric_InitializationVector { get; set; }
        #endregion
        
        #region Parameter OutgoingEncryptionAttributes_Dukpt_InitializationVector
        /// <summary>
        /// <para>
        /// <para>An input to cryptographic primitive used to provide the intial state. Typically the
        /// <code>InitializationVector</code> must have a random or psuedo-random value, but sometimes
        /// it only needs to be unpredictable or unique. If you don't provide a value, Amazon
        /// Web Services Payment Cryptography generates a random value.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        public System.String OutgoingEncryptionAttributes_Dukpt_InitializationVector { get; set; }
        #endregion
        
        #region Parameter OutgoingEncryptionAttributes_Symmetric_InitializationVector
        /// <summary>
        /// <para>
        /// <para>An input to cryptographic primitive used to provide the intial state. The <code>InitializationVector</code>
        /// is typically required have a random or psuedo-random value, but sometimes it only
        /// needs to be unpredictable or unique. If a value is not provided, Amazon Web Services
        /// Payment Cryptography generates a random value.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        public System.String OutgoingEncryptionAttributes_Symmetric_InitializationVector { get; set; }
        #endregion
        
        #region Parameter IncomingEncryptionAttributes_Dukpt_KeySerialNumber
        /// <summary>
        /// <para>
        /// <para>The unique identifier known as Key Serial Number (KSN) that comes from an encrypting
        /// device using DUKPT encryption method. The KSN is derived from the encrypting device
        /// unique identifier and an internal transaction counter.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        public System.String IncomingEncryptionAttributes_Dukpt_KeySerialNumber { get; set; }
        #endregion
        
        #region Parameter OutgoingEncryptionAttributes_Dukpt_KeySerialNumber
        /// <summary>
        /// <para>
        /// <para>The unique identifier known as Key Serial Number (KSN) that comes from an encrypting
        /// device using DUKPT encryption method. The KSN is derived from the encrypting device
        /// unique identifier and an internal transaction counter.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        public System.String OutgoingEncryptionAttributes_Dukpt_KeySerialNumber { get; set; }
        #endregion
        
        #region Parameter IncomingEncryptionAttributes_Dukpt_Mode
        /// <summary>
        /// <para>
        /// <para>The block cipher mode of operation. Block ciphers are designed to encrypt a block
        /// of data of fixed size, for example, 128 bits. The size of the input block is usually
        /// same as the size of the encrypted output block, while the key length can be different.
        /// A mode of operation describes how to repeatedly apply a cipher's single-block operation
        /// to securely transform amounts of data larger than a block.</para><para>The default is CBC.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        [AWSConstantClassSource("Amazon.PaymentCryptographyData.DukptEncryptionMode")]
        public Amazon.PaymentCryptographyData.DukptEncryptionMode IncomingEncryptionAttributes_Dukpt_Mode { get; set; }
        #endregion
        
        #region Parameter IncomingEncryptionAttributes_Symmetric_Mode
        /// <summary>
        /// <para>
        /// <para>The block cipher mode of operation. Block ciphers are designed to encrypt a block
        /// of data of fixed size (for example, 128 bits). The size of the input block is usually
        /// same as the size of the encrypted output block, while the key length can be different.
        /// A mode of operation describes how to repeatedly apply a cipher's single-block operation
        /// to securely transform amounts of data larger than a block.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        [AWSConstantClassSource("Amazon.PaymentCryptographyData.EncryptionMode")]
        public Amazon.PaymentCryptographyData.EncryptionMode IncomingEncryptionAttributes_Symmetric_Mode { get; set; }
        #endregion
        
        #region Parameter OutgoingEncryptionAttributes_Dukpt_Mode
        /// <summary>
        /// <para>
        /// <para>The block cipher mode of operation. Block ciphers are designed to encrypt a block
        /// of data of fixed size, for example, 128 bits. The size of the input block is usually
        /// same as the size of the encrypted output block, while the key length can be different.
        /// A mode of operation describes how to repeatedly apply a cipher's single-block operation
        /// to securely transform amounts of data larger than a block.</para><para>The default is CBC.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        [AWSConstantClassSource("Amazon.PaymentCryptographyData.DukptEncryptionMode")]
        public Amazon.PaymentCryptographyData.DukptEncryptionMode OutgoingEncryptionAttributes_Dukpt_Mode { get; set; }
        #endregion
        
        #region Parameter OutgoingEncryptionAttributes_Symmetric_Mode
        /// <summary>
        /// <para>
        /// <para>The block cipher mode of operation. Block ciphers are designed to encrypt a block
        /// of data of fixed size (for example, 128 bits). The size of the input block is usually
        /// same as the size of the encrypted output block, while the key length can be different.
        /// A mode of operation describes how to repeatedly apply a cipher's single-block operation
        /// to securely transform amounts of data larger than a block.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        [AWSConstantClassSource("Amazon.PaymentCryptographyData.EncryptionMode")]
        public Amazon.PaymentCryptographyData.EncryptionMode OutgoingEncryptionAttributes_Symmetric_Mode { get; set; }
        #endregion
        
        #region Parameter OutgoingKeyIdentifier
        /// <summary>
        /// <para>
        /// <para>The <code>keyARN</code> of the encryption key of outgoing ciphertext data after encryption
        /// by Amazon Web Services Payment Cryptography.</para>
        /// </para>
        /// </summary>
        #if !MODULAR
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        #else
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true, Mandatory = true)]
        [System.Management.Automation.AllowEmptyString]
        [System.Management.Automation.AllowNull]
        #endif
        [Amazon.PowerShell.Common.AWSRequiredParameter]
        public System.String OutgoingKeyIdentifier { get; set; }
        #endregion
        
        #region Parameter IncomingEncryptionAttributes_Symmetric_PaddingType
        /// <summary>
        /// <para>
        /// <para>The padding to be included with the data.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        [AWSConstantClassSource("Amazon.PaymentCryptographyData.PaddingType")]
        public Amazon.PaymentCryptographyData.PaddingType IncomingEncryptionAttributes_Symmetric_PaddingType { get; set; }
        #endregion
        
        #region Parameter OutgoingEncryptionAttributes_Symmetric_PaddingType
        /// <summary>
        /// <para>
        /// <para>The padding to be included with the data.</para>
        /// </para>
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        [AWSConstantClassSource("Amazon.PaymentCryptographyData.PaddingType")]
        public Amazon.PaymentCryptographyData.PaddingType OutgoingEncryptionAttributes_Symmetric_PaddingType { get; set; }
        #endregion
        
        #region Parameter Select
        /// <summary>
        /// Use the -Select parameter to control the cmdlet output. The default value is '*'.
        /// Specifying -Select '*' will result in the cmdlet returning the whole service response (Amazon.PaymentCryptographyData.Model.ReEncryptDataResponse).
        /// Specifying the name of a property of type Amazon.PaymentCryptographyData.Model.ReEncryptDataResponse will result in that property being returned.
        /// Specifying -Select '^ParameterName' will result in the cmdlet returning the selected cmdlet parameter value.
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        public string Select { get; set; } = "*";
        #endregion
        
        #region Parameter Force
        /// <summary>
        /// This parameter overrides confirmation prompts to force 
        /// the cmdlet to continue its operation. This parameter should always
        /// be used with caution.
        /// </summary>
        [System.Management.Automation.Parameter(ValueFromPipelineByPropertyName = true)]
        public SwitchParameter Force { get; set; }
        #endregion
        
        protected override void ProcessRecord()
        {
            this._AWSSignerType = "v4";
            base.ProcessRecord();
            
            var resourceIdentifiersText = string.Empty;
            if (!ConfirmShouldProceed(this.Force.IsPresent, resourceIdentifiersText, "Update-PAYCDEncryptData (ReEncryptData)"))
            {
                return;
            }
            
            var context = new CmdletContext();
            
            // allow for manipulation of parameters prior to loading into context
            PreExecutionContextLoad(context);
            
            if (ParameterWasBound(nameof(this.Select)))
            {
                context.Select = CreateSelectDelegate<Amazon.PaymentCryptographyData.Model.ReEncryptDataResponse, UpdatePAYCDEncryptDataCmdlet>(Select) ??
                    throw new System.ArgumentException("Invalid value for -Select parameter.", nameof(this.Select));
            }
            context.CipherText = this.CipherText;
            #if MODULAR
            if (this.CipherText == null && ParameterWasBound(nameof(this.CipherText)))
            {
                WriteWarning("You are passing $null as a value for parameter CipherText which is marked as required. In case you believe this parameter was incorrectly marked as required, report this by opening an issue at https://github.com/aws/aws-tools-for-powershell/issues.");
            }
            #endif
            context.IncomingEncryptionAttributes_Dukpt_DukptKeyDerivationType = this.IncomingEncryptionAttributes_Dukpt_DukptKeyDerivationType;
            context.IncomingEncryptionAttributes_Dukpt_DukptKeyVariant = this.IncomingEncryptionAttributes_Dukpt_DukptKeyVariant;
            context.IncomingEncryptionAttributes_Dukpt_InitializationVector = this.IncomingEncryptionAttributes_Dukpt_InitializationVector;
            context.IncomingEncryptionAttributes_Dukpt_KeySerialNumber = this.IncomingEncryptionAttributes_Dukpt_KeySerialNumber;
            context.IncomingEncryptionAttributes_Dukpt_Mode = this.IncomingEncryptionAttributes_Dukpt_Mode;
            context.IncomingEncryptionAttributes_Symmetric_InitializationVector = this.IncomingEncryptionAttributes_Symmetric_InitializationVector;
            context.IncomingEncryptionAttributes_Symmetric_Mode = this.IncomingEncryptionAttributes_Symmetric_Mode;
            context.IncomingEncryptionAttributes_Symmetric_PaddingType = this.IncomingEncryptionAttributes_Symmetric_PaddingType;
            context.IncomingKeyIdentifier = this.IncomingKeyIdentifier;
            #if MODULAR
            if (this.IncomingKeyIdentifier == null && ParameterWasBound(nameof(this.IncomingKeyIdentifier)))
            {
                WriteWarning("You are passing $null as a value for parameter IncomingKeyIdentifier which is marked as required. In case you believe this parameter was incorrectly marked as required, report this by opening an issue at https://github.com/aws/aws-tools-for-powershell/issues.");
            }
            #endif
            context.OutgoingEncryptionAttributes_Dukpt_DukptKeyDerivationType = this.OutgoingEncryptionAttributes_Dukpt_DukptKeyDerivationType;
            context.OutgoingEncryptionAttributes_Dukpt_DukptKeyVariant = this.OutgoingEncryptionAttributes_Dukpt_DukptKeyVariant;
            context.OutgoingEncryptionAttributes_Dukpt_InitializationVector = this.OutgoingEncryptionAttributes_Dukpt_InitializationVector;
            context.OutgoingEncryptionAttributes_Dukpt_KeySerialNumber = this.OutgoingEncryptionAttributes_Dukpt_KeySerialNumber;
            context.OutgoingEncryptionAttributes_Dukpt_Mode = this.OutgoingEncryptionAttributes_Dukpt_Mode;
            context.OutgoingEncryptionAttributes_Symmetric_InitializationVector = this.OutgoingEncryptionAttributes_Symmetric_InitializationVector;
            context.OutgoingEncryptionAttributes_Symmetric_Mode = this.OutgoingEncryptionAttributes_Symmetric_Mode;
            context.OutgoingEncryptionAttributes_Symmetric_PaddingType = this.OutgoingEncryptionAttributes_Symmetric_PaddingType;
            context.OutgoingKeyIdentifier = this.OutgoingKeyIdentifier;
            #if MODULAR
            if (this.OutgoingKeyIdentifier == null && ParameterWasBound(nameof(this.OutgoingKeyIdentifier)))
            {
                WriteWarning("You are passing $null as a value for parameter OutgoingKeyIdentifier which is marked as required. In case you believe this parameter was incorrectly marked as required, report this by opening an issue at https://github.com/aws/aws-tools-for-powershell/issues.");
            }
            #endif
            
            // allow further manipulation of loaded context prior to processing
            PostExecutionContextLoad(context);
            
            var output = Execute(context) as CmdletOutput;
            ProcessOutput(output);
        }
        
        #region IExecutor Members
        
        public object Execute(ExecutorContext context)
        {
            var cmdletContext = context as CmdletContext;
            // create request
            var request = new Amazon.PaymentCryptographyData.Model.ReEncryptDataRequest();
            
            if (cmdletContext.CipherText != null)
            {
                request.CipherText = cmdletContext.CipherText;
            }
            
             // populate IncomingEncryptionAttributes
            var requestIncomingEncryptionAttributesIsNull = true;
            request.IncomingEncryptionAttributes = new Amazon.PaymentCryptographyData.Model.ReEncryptionAttributes();
            Amazon.PaymentCryptographyData.Model.SymmetricEncryptionAttributes requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric = null;
            
             // populate Symmetric
            var requestIncomingEncryptionAttributes_incomingEncryptionAttributes_SymmetricIsNull = true;
            requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric = new Amazon.PaymentCryptographyData.Model.SymmetricEncryptionAttributes();
            System.String requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric_incomingEncryptionAttributes_Symmetric_InitializationVector = null;
            if (cmdletContext.IncomingEncryptionAttributes_Symmetric_InitializationVector != null)
            {
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric_incomingEncryptionAttributes_Symmetric_InitializationVector = cmdletContext.IncomingEncryptionAttributes_Symmetric_InitializationVector;
            }
            if (requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric_incomingEncryptionAttributes_Symmetric_InitializationVector != null)
            {
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric.InitializationVector = requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric_incomingEncryptionAttributes_Symmetric_InitializationVector;
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_SymmetricIsNull = false;
            }
            Amazon.PaymentCryptographyData.EncryptionMode requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric_incomingEncryptionAttributes_Symmetric_Mode = null;
            if (cmdletContext.IncomingEncryptionAttributes_Symmetric_Mode != null)
            {
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric_incomingEncryptionAttributes_Symmetric_Mode = cmdletContext.IncomingEncryptionAttributes_Symmetric_Mode;
            }
            if (requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric_incomingEncryptionAttributes_Symmetric_Mode != null)
            {
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric.Mode = requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric_incomingEncryptionAttributes_Symmetric_Mode;
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_SymmetricIsNull = false;
            }
            Amazon.PaymentCryptographyData.PaddingType requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric_incomingEncryptionAttributes_Symmetric_PaddingType = null;
            if (cmdletContext.IncomingEncryptionAttributes_Symmetric_PaddingType != null)
            {
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric_incomingEncryptionAttributes_Symmetric_PaddingType = cmdletContext.IncomingEncryptionAttributes_Symmetric_PaddingType;
            }
            if (requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric_incomingEncryptionAttributes_Symmetric_PaddingType != null)
            {
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric.PaddingType = requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric_incomingEncryptionAttributes_Symmetric_PaddingType;
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_SymmetricIsNull = false;
            }
             // determine if requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric should be set to null
            if (requestIncomingEncryptionAttributes_incomingEncryptionAttributes_SymmetricIsNull)
            {
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric = null;
            }
            if (requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric != null)
            {
                request.IncomingEncryptionAttributes.Symmetric = requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Symmetric;
                requestIncomingEncryptionAttributesIsNull = false;
            }
            Amazon.PaymentCryptographyData.Model.DukptEncryptionAttributes requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt = null;
            
             // populate Dukpt
            var requestIncomingEncryptionAttributes_incomingEncryptionAttributes_DukptIsNull = true;
            requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt = new Amazon.PaymentCryptographyData.Model.DukptEncryptionAttributes();
            Amazon.PaymentCryptographyData.DukptDerivationType requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_DukptKeyDerivationType = null;
            if (cmdletContext.IncomingEncryptionAttributes_Dukpt_DukptKeyDerivationType != null)
            {
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_DukptKeyDerivationType = cmdletContext.IncomingEncryptionAttributes_Dukpt_DukptKeyDerivationType;
            }
            if (requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_DukptKeyDerivationType != null)
            {
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt.DukptKeyDerivationType = requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_DukptKeyDerivationType;
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_DukptIsNull = false;
            }
            Amazon.PaymentCryptographyData.DukptKeyVariant requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_DukptKeyVariant = null;
            if (cmdletContext.IncomingEncryptionAttributes_Dukpt_DukptKeyVariant != null)
            {
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_DukptKeyVariant = cmdletContext.IncomingEncryptionAttributes_Dukpt_DukptKeyVariant;
            }
            if (requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_DukptKeyVariant != null)
            {
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt.DukptKeyVariant = requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_DukptKeyVariant;
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_DukptIsNull = false;
            }
            System.String requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_InitializationVector = null;
            if (cmdletContext.IncomingEncryptionAttributes_Dukpt_InitializationVector != null)
            {
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_InitializationVector = cmdletContext.IncomingEncryptionAttributes_Dukpt_InitializationVector;
            }
            if (requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_InitializationVector != null)
            {
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt.InitializationVector = requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_InitializationVector;
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_DukptIsNull = false;
            }
            System.String requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_KeySerialNumber = null;
            if (cmdletContext.IncomingEncryptionAttributes_Dukpt_KeySerialNumber != null)
            {
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_KeySerialNumber = cmdletContext.IncomingEncryptionAttributes_Dukpt_KeySerialNumber;
            }
            if (requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_KeySerialNumber != null)
            {
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt.KeySerialNumber = requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_KeySerialNumber;
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_DukptIsNull = false;
            }
            Amazon.PaymentCryptographyData.DukptEncryptionMode requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_Mode = null;
            if (cmdletContext.IncomingEncryptionAttributes_Dukpt_Mode != null)
            {
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_Mode = cmdletContext.IncomingEncryptionAttributes_Dukpt_Mode;
            }
            if (requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_Mode != null)
            {
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt.Mode = requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt_incomingEncryptionAttributes_Dukpt_Mode;
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_DukptIsNull = false;
            }
             // determine if requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt should be set to null
            if (requestIncomingEncryptionAttributes_incomingEncryptionAttributes_DukptIsNull)
            {
                requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt = null;
            }
            if (requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt != null)
            {
                request.IncomingEncryptionAttributes.Dukpt = requestIncomingEncryptionAttributes_incomingEncryptionAttributes_Dukpt;
                requestIncomingEncryptionAttributesIsNull = false;
            }
             // determine if request.IncomingEncryptionAttributes should be set to null
            if (requestIncomingEncryptionAttributesIsNull)
            {
                request.IncomingEncryptionAttributes = null;
            }
            if (cmdletContext.IncomingKeyIdentifier != null)
            {
                request.IncomingKeyIdentifier = cmdletContext.IncomingKeyIdentifier;
            }
            
             // populate OutgoingEncryptionAttributes
            var requestOutgoingEncryptionAttributesIsNull = true;
            request.OutgoingEncryptionAttributes = new Amazon.PaymentCryptographyData.Model.ReEncryptionAttributes();
            Amazon.PaymentCryptographyData.Model.SymmetricEncryptionAttributes requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric = null;
            
             // populate Symmetric
            var requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_SymmetricIsNull = true;
            requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric = new Amazon.PaymentCryptographyData.Model.SymmetricEncryptionAttributes();
            System.String requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric_outgoingEncryptionAttributes_Symmetric_InitializationVector = null;
            if (cmdletContext.OutgoingEncryptionAttributes_Symmetric_InitializationVector != null)
            {
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric_outgoingEncryptionAttributes_Symmetric_InitializationVector = cmdletContext.OutgoingEncryptionAttributes_Symmetric_InitializationVector;
            }
            if (requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric_outgoingEncryptionAttributes_Symmetric_InitializationVector != null)
            {
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric.InitializationVector = requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric_outgoingEncryptionAttributes_Symmetric_InitializationVector;
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_SymmetricIsNull = false;
            }
            Amazon.PaymentCryptographyData.EncryptionMode requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric_outgoingEncryptionAttributes_Symmetric_Mode = null;
            if (cmdletContext.OutgoingEncryptionAttributes_Symmetric_Mode != null)
            {
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric_outgoingEncryptionAttributes_Symmetric_Mode = cmdletContext.OutgoingEncryptionAttributes_Symmetric_Mode;
            }
            if (requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric_outgoingEncryptionAttributes_Symmetric_Mode != null)
            {
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric.Mode = requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric_outgoingEncryptionAttributes_Symmetric_Mode;
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_SymmetricIsNull = false;
            }
            Amazon.PaymentCryptographyData.PaddingType requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric_outgoingEncryptionAttributes_Symmetric_PaddingType = null;
            if (cmdletContext.OutgoingEncryptionAttributes_Symmetric_PaddingType != null)
            {
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric_outgoingEncryptionAttributes_Symmetric_PaddingType = cmdletContext.OutgoingEncryptionAttributes_Symmetric_PaddingType;
            }
            if (requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric_outgoingEncryptionAttributes_Symmetric_PaddingType != null)
            {
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric.PaddingType = requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric_outgoingEncryptionAttributes_Symmetric_PaddingType;
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_SymmetricIsNull = false;
            }
             // determine if requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric should be set to null
            if (requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_SymmetricIsNull)
            {
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric = null;
            }
            if (requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric != null)
            {
                request.OutgoingEncryptionAttributes.Symmetric = requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Symmetric;
                requestOutgoingEncryptionAttributesIsNull = false;
            }
            Amazon.PaymentCryptographyData.Model.DukptEncryptionAttributes requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt = null;
            
             // populate Dukpt
            var requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_DukptIsNull = true;
            requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt = new Amazon.PaymentCryptographyData.Model.DukptEncryptionAttributes();
            Amazon.PaymentCryptographyData.DukptDerivationType requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_DukptKeyDerivationType = null;
            if (cmdletContext.OutgoingEncryptionAttributes_Dukpt_DukptKeyDerivationType != null)
            {
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_DukptKeyDerivationType = cmdletContext.OutgoingEncryptionAttributes_Dukpt_DukptKeyDerivationType;
            }
            if (requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_DukptKeyDerivationType != null)
            {
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt.DukptKeyDerivationType = requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_DukptKeyDerivationType;
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_DukptIsNull = false;
            }
            Amazon.PaymentCryptographyData.DukptKeyVariant requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_DukptKeyVariant = null;
            if (cmdletContext.OutgoingEncryptionAttributes_Dukpt_DukptKeyVariant != null)
            {
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_DukptKeyVariant = cmdletContext.OutgoingEncryptionAttributes_Dukpt_DukptKeyVariant;
            }
            if (requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_DukptKeyVariant != null)
            {
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt.DukptKeyVariant = requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_DukptKeyVariant;
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_DukptIsNull = false;
            }
            System.String requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_InitializationVector = null;
            if (cmdletContext.OutgoingEncryptionAttributes_Dukpt_InitializationVector != null)
            {
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_InitializationVector = cmdletContext.OutgoingEncryptionAttributes_Dukpt_InitializationVector;
            }
            if (requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_InitializationVector != null)
            {
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt.InitializationVector = requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_InitializationVector;
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_DukptIsNull = false;
            }
            System.String requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_KeySerialNumber = null;
            if (cmdletContext.OutgoingEncryptionAttributes_Dukpt_KeySerialNumber != null)
            {
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_KeySerialNumber = cmdletContext.OutgoingEncryptionAttributes_Dukpt_KeySerialNumber;
            }
            if (requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_KeySerialNumber != null)
            {
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt.KeySerialNumber = requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_KeySerialNumber;
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_DukptIsNull = false;
            }
            Amazon.PaymentCryptographyData.DukptEncryptionMode requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_Mode = null;
            if (cmdletContext.OutgoingEncryptionAttributes_Dukpt_Mode != null)
            {
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_Mode = cmdletContext.OutgoingEncryptionAttributes_Dukpt_Mode;
            }
            if (requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_Mode != null)
            {
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt.Mode = requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt_outgoingEncryptionAttributes_Dukpt_Mode;
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_DukptIsNull = false;
            }
             // determine if requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt should be set to null
            if (requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_DukptIsNull)
            {
                requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt = null;
            }
            if (requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt != null)
            {
                request.OutgoingEncryptionAttributes.Dukpt = requestOutgoingEncryptionAttributes_outgoingEncryptionAttributes_Dukpt;
                requestOutgoingEncryptionAttributesIsNull = false;
            }
             // determine if request.OutgoingEncryptionAttributes should be set to null
            if (requestOutgoingEncryptionAttributesIsNull)
            {
                request.OutgoingEncryptionAttributes = null;
            }
            if (cmdletContext.OutgoingKeyIdentifier != null)
            {
                request.OutgoingKeyIdentifier = cmdletContext.OutgoingKeyIdentifier;
            }
            
            CmdletOutput output;
            
            // issue call
            var client = Client ?? CreateClient(_CurrentCredentials, _RegionEndpoint);
            try
            {
                var response = CallAWSServiceOperation(client, request);
                object pipelineOutput = null;
                pipelineOutput = cmdletContext.Select(response, this);
                output = new CmdletOutput
                {
                    PipelineOutput = pipelineOutput,
                    ServiceResponse = response
                };
            }
            catch (Exception e)
            {
                output = new CmdletOutput { ErrorResponse = e };
            }
            
            return output;
        }
        
        public ExecutorContext CreateContext()
        {
            return new CmdletContext();
        }
        
        #endregion
        
        #region AWS Service Operation Call
        
        private Amazon.PaymentCryptographyData.Model.ReEncryptDataResponse CallAWSServiceOperation(IAmazonPaymentCryptographyData client, Amazon.PaymentCryptographyData.Model.ReEncryptDataRequest request)
        {
            Utils.Common.WriteVerboseEndpointMessage(this, client.Config, "Payment Cryptography Data", "ReEncryptData");
            try
            {
                #if DESKTOP
                return client.ReEncryptData(request);
                #elif CORECLR
                return client.ReEncryptDataAsync(request).GetAwaiter().GetResult();
                #else
                        #error "Unknown build edition"
                #endif
            }
            catch (AmazonServiceException exc)
            {
                var webException = exc.InnerException as System.Net.WebException;
                if (webException != null)
                {
                    throw new Exception(Utils.Common.FormatNameResolutionFailureMessage(client.Config, webException.Message), webException);
                }
                throw;
            }
        }
        
        #endregion
        
        internal partial class CmdletContext : ExecutorContext
        {
            public System.String CipherText { get; set; }
            public Amazon.PaymentCryptographyData.DukptDerivationType IncomingEncryptionAttributes_Dukpt_DukptKeyDerivationType { get; set; }
            public Amazon.PaymentCryptographyData.DukptKeyVariant IncomingEncryptionAttributes_Dukpt_DukptKeyVariant { get; set; }
            public System.String IncomingEncryptionAttributes_Dukpt_InitializationVector { get; set; }
            public System.String IncomingEncryptionAttributes_Dukpt_KeySerialNumber { get; set; }
            public Amazon.PaymentCryptographyData.DukptEncryptionMode IncomingEncryptionAttributes_Dukpt_Mode { get; set; }
            public System.String IncomingEncryptionAttributes_Symmetric_InitializationVector { get; set; }
            public Amazon.PaymentCryptographyData.EncryptionMode IncomingEncryptionAttributes_Symmetric_Mode { get; set; }
            public Amazon.PaymentCryptographyData.PaddingType IncomingEncryptionAttributes_Symmetric_PaddingType { get; set; }
            public System.String IncomingKeyIdentifier { get; set; }
            public Amazon.PaymentCryptographyData.DukptDerivationType OutgoingEncryptionAttributes_Dukpt_DukptKeyDerivationType { get; set; }
            public Amazon.PaymentCryptographyData.DukptKeyVariant OutgoingEncryptionAttributes_Dukpt_DukptKeyVariant { get; set; }
            public System.String OutgoingEncryptionAttributes_Dukpt_InitializationVector { get; set; }
            public System.String OutgoingEncryptionAttributes_Dukpt_KeySerialNumber { get; set; }
            public Amazon.PaymentCryptographyData.DukptEncryptionMode OutgoingEncryptionAttributes_Dukpt_Mode { get; set; }
            public System.String OutgoingEncryptionAttributes_Symmetric_InitializationVector { get; set; }
            public Amazon.PaymentCryptographyData.EncryptionMode OutgoingEncryptionAttributes_Symmetric_Mode { get; set; }
            public Amazon.PaymentCryptographyData.PaddingType OutgoingEncryptionAttributes_Symmetric_PaddingType { get; set; }
            public System.String OutgoingKeyIdentifier { get; set; }
            public System.Func<Amazon.PaymentCryptographyData.Model.ReEncryptDataResponse, UpdatePAYCDEncryptDataCmdlet, object> Select { get; set; } =
                (response, cmdlet) => response;
        }
        
    }
}
