name: Closed Issue Message
on:
    issues:
       types: [closed]
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}

jobs:
    auto_comment:
        name: Auto comment on closed issue
        runs-on: ubuntu-latest
        permissions:
          issues: write # to comment on the closed issue
        steps:
        - uses: aws-actions/closed-issue-message@cf797c2463fa6b95a23b2957fe075a3fa9aa8138 # v1
          with:
            # These inputs are both required
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
            message: |
                     ### ⚠️COMMENT VISIBILITY WARNING⚠️ 
                     Comments on closed issues are hard for our team to see. 
                     If you need more assistance, please either tag a team member or open a new issue that references this one. 
                     If you wish to keep having a conversation with other community members under this issue feel free to do so.
