name: Validate Documentation Metadata

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-doc-metadata:
    name: Validate Doc Metadata
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
      - name: validate metadata
        uses: awsdocs/aws-doc-sdk-examples-tools@main
